scieloorg/opac

- Makefile
- app/__init__.py
- app/admin/forms.py
- app/admin/views.py
- app/main/views.py
- app/templates/admin/auth/login.html
- app/templates/admin/auth/reset.html
- app/templates/admin/auth/reset_with_token.html
- app/templates/admin/auth/unconfirm_email.html
- app/templates/admin/index.html
- app/templates/admin/opac_base.html
- app/templates/collection/index.html
- app/translations/en/LC_MESSAGES/messages.po
- app/translations/es/LC_MESSAGES/messages.po
- app/utils.py
- config/babel.cfg
- config/default.py
- requirements.txt
* Definir quais são os idiomas suportados
* Definido: pt_BR, ES, EN
* Definir estratégia de decisão do idioma para o usuário (Quando abrir um recurso da app qual será o idioma?)
* No primeiro acesso ao site, vai ser segundo o sugerido pelo cabeçalho: [``Accept-Language``](http://www.w3.org/International/questions/qa-lang-priorities.en.php),
* O usuário pode trocar o idioma visitando os links (view function: ``set_locale``), a escolha do idioma fica salvo na sessão.
* instalar as dependências e configurações necessárias para ter a funcionalidade de i18n.
* Para isso foi utilzado ``Flask-Babelex``, um fork do ``Flask-Babel`` sugerido pela documentação oficial do  [``Flask-Admin``](https://flask-admin.readthedocs.org/en/latest/advanced/#localization-with-flask-babelex)
Os textos traduzíveis …
> #12 - Adicionar a capacidade de i18n.

- .travis.yml
- Makefile
- config/testing.py
- manager.py
- requirements.txt
- tests/test_basic.py
- tests/test_main_views.py
Setup e instalação para poder trabalhar com tests unitários.
- makefile tem um comando para executar os tests: ``make  test``
- tests simples foram criados na pasta ``/opac/tests/``
Também foi adicionado um arquivo: ``.travis.yml`` para integração com travis-ci
> #14 - Definições para implementação dos testes unitários

- Makefile
- app/admin/views.py
- app/translations/en/LC_MESSAGES/messages.po
- app/translations/es/LC_MESSAGES/messages.po
- app/translations/messages.pot
Fix #40 
Se requiere actualizar la versión de Flask-Admin a la version 1.4.0 ya que la actual tiene un problema al utilizar column_filters y column_label con traducciones (los elementos dentro de column_filters mandan mensaje de error)
> Add column_labels to ModelView’s

- app/__init__.py
- app/admin/views.py
- app/controllers.py
- app/translations/en/LC_MESSAGES/messages.po
- app/translations/es/LC_MESSAGES/messages.po
- app/translations/messages.pot
- config/testing.py
- manager.py
1. Importar o novo modelo (OPAC schema) que armazena metadados da Coleção (ver: [0]);
2. Importar o novo *Documento* (OPAC schema) que armazena metadados de Sponsor (ver: [0]);
3. Implementar a capacidade de associar um ou mais sponsors a uma coleção (via ``/admin/``).
- `` app/admin/views.py`` aonde são definidas as novas views de Admin, para coleção e financiador;
- ``app/__init__.py`` aonde estão associadas as novas views com o app.
**IMPORANTE:** veja abaixo os pré-requisitos.
1. acessar no admin com usuário válido;
2. pelo menu acessar em *Sponsors*/*Financiadores*;
3. criar alguns financiadores;
4. pelo menu acessar a: *Collections*/*Coleções*;
5. deve existir uma coleção criada, acesse para editar essa coleção;
6. associar um ou mais financiadores na coleção.
- é necessário ter a …
> #17 - R6. O sistema deve permitir associar a lista de sponsor por coleção

- app/admin/views.py
- app/main/errors.py
- app/models.py
- app/notifications.py
- config/testing.py
- manager.py
- tests/test_admin_views.py
tests para:
- redirect no acesso ao admin
- logins inválidos (de varias formas) ao admin
- erros de validação no login
- login válido
- link de recuperar senha no login
- links de trocar idioma no login
- logout ok!
- pagina e form de password reset
- submit no reset password para usuário inválido
- submit no reset password para usuário válid
- reset password com token (resposta do usuário ao clickar no email)
- views de confirmação do email
**obs:**
tem *skip* para pular 2 casos, quando é cadastrado um novo usuário via Admin, que ainda não estão funcionando. Deixei a pergunta em: http://stackoverflow.com/q/35364903/1503 esperando alguma ajuda
> #74 - Testes para o ``admin.views``

- tests/test_main_errors.py
Para que el test del error 500 funcione como debe ser (un verdadero internal server error) fue necesario cambiar la configuración:
```current_app.config['DEBUG'] = False``` Esto porque con un valor de ```True``` flask nos muestra el log del error en lugar del error personalizado
```current_app.config['TESTING'] = False``` Esto porque con un valor de ```True```:
```What it does is disabling the error catching during request handling so that you get better error reports when performing test requests against the application```(http://flask.pocoo.org/docs/0.10/testing/)
Lo que provoca que el error no sea mostrado durante el request que es el momento en el cual ocurre el error 500 y se puede hacer el manejo del error personalizado.
También se puede forzar el error con un ```abort(500)``` y en …
> Agregados tests para main.errors

- app/notifications.py
- app/utils.py
- requirements.dev.txt
- tests/test_notifications.py
Fix #95
Cobertura de las pruebas de 87%, no se bien como reproducir las excepciones:
https://github.com/scieloorg/opac/blob/master/app/notifications.py#L24
https://github.com/scieloorg/opac/blob/master/app/notifications.py#L45
Hasta donde veo solo se podría reproducir una excepción  de [Bad Data,](http://pythonhosted.org/itsdangerous/#itsdangerous.BadData) pero ahora se verifica que `recipient_email` sea un correo electrónico válido, entonces no si se exista otra forma de entrar a la excepciones?
> Agregados tests para notifications

- opac/manager.py
- opac/tests/base.py
- opac/tests/test_admin_custom_filters.py
- opac/tests/test_admin_views.py
- opac/tests/test_interface_journal_home.py
- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/__init__.py
- opac/webapp/admin/custom_filters.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/models.py
- opac/webapp/templates/journal/includes/contact_footer.html
- requirements.dev.txt
- requirements.production.txt
- requirements.txt
FIX: #254 
- atualização de dependências
- ajustes nos imports (``flask.ext.*`` levanta DeprecationWarning a partir de ``Flask==0.11``)
- Flask debug toolbar agora mostra as queries do MongoDB (quando ``DEBUG=True``)
- As redes sociais do Periódico, serão exibidas somente quando são cadastradas.
> #254 - remover redes socials periodicos

- opac/tests/test_interface_menu.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/alternative_header.html
- opac/webapp/templates/collection/includes/nav.html
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/collection/list_journal.html
- opac/webapp/templates/issue/base.html
- opac/webapp/templates/issue/grid.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/journal/includes/header.html
Itens realizados nesse PR: 
* Ajustes nos links hambuger quanto esta na mesma página (tabs).
* Na listagem por área temática garantir que o cabeçalho da tabela seja coerente com Grandes Areas e Web of Science
* Ajustes nos templates de download nas listagens para que não esteja com None ou caracteres estranhos (None #issue etc)
* Garantir que os links para as métricas abra em outra janela não perdendo o contexto do site SciELO
* Evitado mostrar None quando não tem missão
* No Menu superior adicionar a legenda bibliográfica, contextualizado por fascículo e por periódico
* Garantindo que não tenha um erro 500 no feed da home do periódico
* Não apresentar o espaço para o logo caso não exista logo para o periódico
> Several interface itens

- opac/webapp/controllers.py
- opac/webapp/static/css/style.css
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/collection/list_journal.html
- opac/webapp/templates/issue/grid.html
Atividades realizadas nesse PR:
1. Ocultado a lista de instituições
2. Números das métricas na ordem que esta no analytics
3. Volume não pode ser um link
4. Para volume issue inserir inserido o link "X artigos"
5. Ahead of print: nova linha (em primeiro lugar) sem ano nem volume, na célula de número colocar o botão de ahead of print.
6. Novos periódicos
7. Eliminar Métricas
Esse ticket é referente aos tickets: #323, #322, #320, #319.
> Ajustes referente aos ajustes da reunião do dia 30/09/2016

- opac/webapp/admin/views.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/detail.html
FIX #370
- Adicionado o ano atual junto ao índice e mediana. Porque cada h5m5 processado é com o ano atual;
- Adicionado o filtro `|safe` no texto da missão pq vem com tags html (exemplo, periódico `resp`);
- removido `import datetime` não utilizado.
> FIX 370 - Adicionar o ano no índice h5

- Dockerfile
- Dockerfile-dev
FIX #399
Agora na saída do comando: `docker ps` (ou `docker container ls`) deve aparecer após os primeiros 5 mintuos de execução:
`Up 5 minutes (healthy)` na linha do container apac_webapp
Obs: precisa instalar o `curl`
> FIX 399 - acrescentar instrução HEALTHCHECK no Dockefile

- Dockerfile
- Dockerfile-dev
- opac/tests/test_admin_views.py
- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/webapp/admin/views.py
- opac/webapp/choices.py
FIX #411
Antes tinhamos 3 opções:
- 'Problema de Direito Autoral'
- 'Plágio'
- 'Abuso ou Conteúdo Indevido'
Mas em discussão com a equipe, foi decidido deixar só uma:
- 'Conteúdo temporariamente indisponível'
> Fix 411 - Ajuste das unpublishing reasons

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/recent_articles_row.html
- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/templates/collection/list_feed_content.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/about.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/header.html
- FIX: #610
- FIX: tirando espácos em branco de tags {% trans %}
- FIX: indentação em 2 espaços nos tempaltes
- FIX: lista de redes socials na página about agora iterar nos dados. Antes estava cravado.
> FIX na legenda bibliografica (issue: 610) e outros ajustes menores

- opac/manager.py
- opac/webapp/__init__.py
- opac/webapp/config/default.py
- opac/webapp/utils.py
Fixes #630 
É necessário termos uma pasta montada no servidor do OPAC com o path para as páginas secundárias.
> Adicionando comando para carregar as páginas secundárias

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- requirements.txt
FIX: #689
- falta ajustar a query para filtar por um novo campo: `assets_code`
- atualizar o OPAC Schema com o novo campo: `assets_code`
Refs:
- campo `assets_code` no XYLOSE article: https://github.com/scieloorg/xylose/blob/e585f7f6944ab048b0b4cd625bf399b8a30d418f/xylose/scielodocument.py#L1556
> suporte para urls de PDF do legado

- opac/manager.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/notifications.py
- opac/webapp/utils/journal_static_page.py
- opac/webapp/utils/utils.py
- remove o header e o footer das páginas secundárias que são padronizados pois fazem parte de um template dreamweaver
- retira de dentro de um for o bloco de tratamento das imagens
- cria uma pasta utils e dentro dela passa a ter utils + journal_static_page
> ajustes_conteudo_paginas_secundarias

- Makefile
- opac/manager.py
FIX: #783
Exemplos:
No ambiente de dev:
- `make dev_compose_invalidate_cache` e digitar "y" para confirmação;
- `make dev_compose_invalidate_cache_forced` e não precisa digitar confirmação.
No server:
- `make invalidate_cache` e digitar "y" para confirmação;
- `make invalidate_cache_forced` e não precisa digitar confirmação.
> Add comando invalidate_cache (opção de forçar ou confirmação do usuário)

- opac/manager.py
- opac/webapp/main/views.py
- opac/webapp/utils/caching.py
- opac/webapp/utils/utils.py
FIX: #785 
1. Acessar o shell do opac
2. Executar o comando `python manage.py invalidate_cache_pattern <ARGS>`
- `--force` (opcional) quando indicado, não vai pedir confirmação para o usuário;
- `--pattern` (obrigatorio, posicional) valor do pattern para filtar (tem que estar entre aspas)
1. `$ make dev_compose_exec_shell_webapp` acessamos o shell do container de dev;
2. `cd opac/` vamos para o diretório do projeto;
3. Vemos as opções para usar o comando:  `python manager.py invalidate_cache_pattern -?`. Saida:
```
usage: manager.py invalidate_cache_pattern [-?] [-f] pattern
positional arguments:
pattern
optional arguments:
-?, --help         show this help message and exit
-f, --force_clear
```
- `python manager.py invalidate_cache_pattern '*'` (vai pedir confirmação do usuário);
- …
> Improve cache clean with patterns

- opac/webapp/static/js/ckeditor/config.js
Ajuste para permitir a inserção de imagens no conteúdo, previamente precisa conhecer a URL da imagem:
> FIX: habilitando o widget de upload de imagem simples

- opac/webapp/admin/views.py
- opac/webapp/choices.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/about.html
- opac/webapp/templates/includes/page_updated_at_info.html
- opac/webapp/templates/journal/about.html
FIX: #879
AJUSTES:
- labels traduzíveis: `Data de Criação`, `Data de Atualização`
- adicionado filtros pelas colunas: 'name', 'language', 'journal', 'created_at', 'updated_at'
- adicionado search pelas colunas: 'name', 'description', 'content',
- formatação de datas na listagem de Pages no admin
- os campos de datas foram removidos do form de create/update
> FIXES (879): datas de criação e atualização de pag.info

- opac/webapp/admin/views.py
os formatters das colunas: `created_at` e `updated_at` quebram quando no modelo não estão definidos.
este fix contorna esta situação, porém podemos considerar que os campos sempre estarão presentes (por padrão são definidos no evento save do modelo Page) e porque foi apontado para definir uma data de criação igual al dia do lançamento do site.
> fix: campos created_at e updated_at não quebra quando não estão definidos

- Dockerfile
- Dockerfile-dev
- opac/manager.py
- opac/tests/pages/aa/eedboard.htm
- opac/tests/pages/abb/einstruc.htm
- opac/tests/pages/abb/pinstruc.htm
- opac/tests/pages/ea/iinstruc.htm
- opac/tests/pages/ea/pinstruc.htm
- opac/tests/pages/eagri/pedboard.htm
- opac/tests/pages/eins/eedboard.htm
- opac/tests/test_utils_journal_static_page.py
- opac/webapp/config/default.py
- opac/webapp/utils/journal_static_page.py
- opac/webapp/utils/utils.py
- requirements.txt
- uso de BeautifulSoup + lxml
- remoção de âncoras desnecessárias
- troca de ``<p class="subtitulo">`` por ``<b>`` pois dentro do site novo os "subtítulos" ficavam sem bold
- ajustes na remoção de cabeçalhos (logo do periódico etc) e rodapés (links de navegação) das páginas originais
- remoção da multiplicidade de textos "Conteúdo indisponível na versão do idioma da interface", mantendo apenas 1 vez. (Como a página informativa é formada pelo conteúdo de 3 páginas do site antigo, no site novo a mesma mensagem ficava repetida 3 vezes).
- testes
> [tk985] Melhorias no procedimento de carga das páginas informativas

- opac/tests/test_main_views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Adicionar na URL do legado a pesquisa por Ahead.
> Adiciona a capacidade da URL antiga do SciELO responda para o PID de Ahead

- opac/webapp/templates/base.html
Alteração do cabeçalho para SciELO - <nome da coleção>.
Assim, aparecerá:
- spa: SciELO - Saúde Pública
- scl: SciELO - Brasil
OBS: será necessário alterar o cadastro para retirar "SciELO" e ficar somente "Brasil"
> Alteração do cabeçalho da página

- opac/tests/test_utils_journal_static_page.py
- opac/webapp/utils/journal_static_page.py
- Geração e inclusão de título para as âncoras no conteúdo da página
- Testes para:
- atributo jspf.anchor_title
- verificar se o título da âncora está presente no conteúdo da página
Fixes #1016
> [tk1016] Incluir título para as âncoras (about, editors, instructions) 

- opac/tests/test_interface_journal_home.py
- opac/webapp/config/default.py
- opac/webapp/templates/journal/detail.html
- requirements.txt
- setup.py
- Uso de variáveis de ambiente:
- SCIMAGO_URL (default: 'https://www.scimagojr.com/journalsearch.php?tip=sid&clean=0&q=')
- SCIMAGO_ENABLED (default: True)
- Apresenta URL somente se periódico tem scimago_id e se SCIMAGO_ENABLED is True
Fixes #983
> [tk983] Apresentação do link Scimago na home do periódico

- opac/webapp/templates/journal/base.html
O consultor do Varnish sinalizou o seguinte problema: 
> Guillaume Quintard (Varnish Software)Oct 20, 08:15 CESTHi,
> 
> I've been poking around, and the first issue (error message in the footer) is fairly straightforward: we get a 404 because the location is "/form_contact//", which looks like a problem with a missing/empty variable. Does this ring a bell?
> 
Esse PR corrigi a o caminho para o form de contato.
> Corrigi atributo para a url do formulário de contato

- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/about.html
Como alguns slug_name podem ficar identicos, usar o language para distinguir.
Fixes #1081
> [tk1081] Páginas about acessíveis com slug_name e language

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/base.html
Correções de erros encontrados na revisão em homologação:
- fix: parametro config na URL do js.
- add: namespace do MathML na tag `<html...>` somente para os templates de artigos
no arquivo de configuração `default.py` que adiciona a variável de ambiente para configurar a URL da lib JS.
Acessando um artigo com formula matemática. Em homologação temos: 
https://homolog.opac.scielo.br/scielo.php?pid=S0044-59672017000300175&script=sci_arttext
uma formula na seção: **Statistical analysis**.
Anteriormente não foi adicionado o **namespace** pela recomendação da documentação. Mas conferindo que não funcionou, estamos tentando com o namespace.
Fragmento da [documentação](http://docs.mathjax.org/en/latest/start.html#mathml-input): 
```
Note that even on old browsers this will work in HTML files, …
```
> fix: url do js MATHML com config certo e add namespace na tag html

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Retornar apenas documentos dos tipos:
- article-commentary
- brief-report
- case-report
- rapid-communication
- research-article
- review-article
Com o objetivo de dar destaques a documentos mais relevantes na página principal do periódico na seção "Artigos mais recentes" 
opac/webapp/controllers.py
linha 837
issue #885 
tk885
> get_recent_articles_of_issue deve retornar somente documentos do tipo "citável":

- opac/webapp/main/views.py
- opac/webapp/templates/collection/list_journal.html
Hoje, ao acessar a lista temática de periódicos e alterar o idioma, ao invés de manter-se na aba temática, muda para a aba alfabética.
Pela view `set_locale` em `main/view.py`
- Acesse a lista de periódicos em ordem alfabética. Altere para a aba por área temática e mude o idioma. A lista por área temática deve continuar sendo exibida com o idioma alterado.
- Acesse outras páginas (página principal, home do periódico, , artigo etc) e altere o idioma, para garantir que a alteração não afetou a mudança de idioma em outras partes.
N/A
#835 
N/A
N/A
> Corrige mudança de idioma na lista temática de periódicos

- opac/tests/test_utils.py
- opac/tests/test_utils_page_migration.py
- opac/webapp/utils/page_migration.py
Corrige o conteúdo das páginas secundárias que, ao ser alterado, estava gerando um erro por conta do _parser_ de HTML utilizado para o conteúdo.
Property `MigratedPage.content` em `webapp/utils/page_migration.py`
- Altere uma página secundária existente e tente visualizá-la.
- Crie uma página secundária nova e tente visualizá-la.
A aplicação utiliza o Flask-HTMLmin que mimifica os responses do Flask de mime type `text/html`. Ele utiliza o htmlmin e seu parser valida se há outras tags além da tag `html` que fecha todo o conteúdo. Como o conteúdo das páginas secundárias está sendo parseado na aplicação com o BeautifulSoup, utilizando o parser `lxml`, o objeto retornado é criado com as tags `html` e `body`, que conflitam com as tags da página da aplicação. 
#1145
N/A
N/A
> Corrige a alteração do conteúdo das Páginas Secundárias no Admin

- requirements.txt
Ao atualizar o ambiente, a seguinte exceção ocorreu:
```
Traceback (most recent call last):
File "/usr/local/bin/rq", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File …
```
> Atualiza versão do RQ para corrigir exceção

- opac/webapp/controllers.py
Fix: #1129
Após a adição do título da página no formulário de erro, identificamos um problema de interpolação de texto na construção da mensagem para o usuário.
> Corrigi a interpolação na msg de erro (e-mail)

- opac/webapp/templates/article/includes/modal/related_article.html
Corrige o conteúdo da janela modal onde deveria apresentar links para Google e Google Scholar, pois os links não estavam funcionando, aparentemente por haver mudado o link de busca.
/opac/webapp/main/views.py, linha 862
Após o deploy, entre na página de um artigo, por exemplo: https://new.scielo.br/scielo.php?pid=S0100-879X2004000400003&script=sci_arttext, acesse o menu flutuante na lateral esquerda inferior, clicar no último ícone (Artigos relacionados ou artigos e similares). Testar os links que aparecem na janela modal.
como a forma de criar os links para Google e Google Scholar podem mudar, decidi criar funções que geram os dados para apresentar o conteúdo do modal. Veja /opac/webapp/utils/related_articles_urls.py
#891 
Ver no issue #891
> [tk891] Corrige o conteúdo da janela modal onde deveria apresentar links para Google e Google Scholar

- opac/webapp/templates/news/includes/issue_last_row.html
fix #970 
Alterada a tag a de lugar. Dessa maneira todo o corpo do box cinza torna-se clicável.
> alterada a tag a de local para tornar todo o box cinza clicável

- opac/webapp/choices.py
- opac/webapp/controllers.py
- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Adicionado razão da descontinuidade do periódico na listagem de periódicos descontinuados do OPAC, 
verificar o `controler.py` a adição de uma nova chave ao dicionário com a razão da descontinuidade do periódico
Na lista de periódicos descontinuados agora deve aparecer entre parênteses o motivo pela descontinuidade do periódico, igual acontece no site atual
https://github.com/scieloorg/opac/issues/1117
> Adicionado razão da descontinuidade do periódico na listagem

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/base.html
Atualiza o endereço para o javascript do **Plumx** e realiza algumas alteração de URL para uso de http e https.
Verificar manualmente o endereço do Plumx no arquivo: opac/webapp/templates/article/base.html
Acessando um página de artigo o modal de métricas, ver:
#1136
> Atualizar widget PlumX

- opac/tests/test_utils_journal_static_page.py
* Ao executar os testes no docker quando localmente não é levantando a exceção de erro no teste: test_insert_middle_end_bjmbr_iinstruct, porém o travis indica que existe uma erro nesse teste.
Pelo 'opac/tests/test_utils_journal_static_page.py'
Rodando os testes localmente ou utilizando o comando do docker: 
- make dev_compose_make_test
- export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test
Tela de erro do travis: 
Não há.
> Evitar erro de testes no Travis

- opac/webapp/controllers.py
- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- requirements.txt
* No cabeçalho do periódico do título antigo adiciona o link para o título novo:
* No cabeçalho do periódico do título novo adiciona o link para o título antigo:
Pelo 'controllers.py' e 'journal/includes/header.html'
na listagem de periódicos e na visualização do periódico inativos e do periódico ativo que o referencia  
https://github.com/scieloorg/opac/issues/1117
> Adiciona Link referencia cruzada entre os periódicos ativos e inativos

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/about.html
- requirements.txt
Foi removido o `lang` da URL assim a solução dada foi que os `slug_name` das paginas do sobre deve ser iguais, nos 3 idiomas, assim é possível o vínculos das paginas. E caso a aplicação não encontre uma slug_name, no idioma atual da sessão o usuario sera redirecionado a listagem das paginas do sobre
Pelo `main/views.py`
Apos atualizar o ambiente, e criar as 3 paginas com a mesma `slug_name`, mas languages diferentes acesse o ambiente opac, e alterne os idiomas
Apos a atualização do ambiente sera necessário alterar os `slug_name` das paginas manualmente, e sempre manter esse padrão para as novas paginas que forem criadas na aplicação
#1130
> [TK #1130] Páginas about devem ter vínculos entre os idiomas

- opac/tests/test_interface_journal_home.py
- opac/webapp/choices.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Traduz as áreas temáticas da home do periódico e remove as "subject categories" (categorias temáticas do WoS)
opac/webapp/main/views.py, linha 328:
```
@main.route('/journal/<string:url_seg>/')
```
Entrar em páginas home de periódicos e visualizar a localização de "Área:"
Diante de área devem aparecer todas as áreas traduzidas
As áreas temáticas são constantes já usadas desde o início de SciELO. São as mesmas apresentadas em https://new.scielo.br/journals/#theme
As traduções foram definidas em choices.py.
Desde o início houve um erro no código das áreas temáticas. No lugar de LETTER, deveria ser LITERATURE. Por isso, ao traduzir para o inglês, é traduzido como LITERATURE.
#1187 
Durante o processo de resolução desta questão, foi identificado um bug #1201, que é problema ao popular os …
> [tk1116] Traduzir as áreas temáticas da home do periódico

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- requirements.txt
- Ajusta a view `article_detail_pid` para, caso não encontrar o artigo
pelo PID, buscar artigos com `aop_pid` com o valor
- Ajustar a view `article_detail` para, caso não encontrar o artigo pelo
`url_segment` do artigo, buscar pelos url_segments de AOP
Em `opac/webapp/main/views.py`, na view `article_detail`
Tentar acessar um ex-ahead of print que já tenha sido publicado em um fascículo regular mas usando a URL de ahead.
Detalhes descritos em #937.
N/A.
#937.
Nenhuma.
> Tratamento de URL do ahead of print na publicação do ex-ahead

- docker-compose-build.yml
- docker-compose-dev.yml
- docker-compose.yml
- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/includes/metric_modal.html
Este pull request adiciona o widget do Altmetric na modal de métricas dos artigos.
- `./docker-compose.yml`
- `opac/webapp/config/default.py`
- `opac/webapp/templates/includes/metric_modal.html`
- Acessando a página de um artigo
- Clicando no indicador de métricas
- Clicando no ícone do Altmetric
N/A
1. Artigo com dados do altmetric
2. Artigo sem dados do altmetric
#1131
http://api.altmetric.com/embeds.html
> Adiciona o Altmetric na modal de métricas de artigos

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- Corrige campo para agrupamento de periódicos (áreas temáticas exibia
as categorias de WoS e vice-versa)
- Traduz lista de áreas temáticas de acordo com o idioma selecionado
Em `opac/webapp/controllers.py`, na função `get_journals_grouped_by`
Ao acessar a lista de periódicos por áreas temáticas, agrupados pelas grandes áreas de conhecimento, lista deve ser exibida com o idioma da interface. Se o idioma for alterado, deve exibir a lista com a tradução correta.
N/A
N/A
#1157 
Nenhuma.
> Corrige Lista de áreas temáticas

- opac/webapp/main/views.py
- Retorna para a home do periódico as seções e artigos recentes somente
se o periódico estiver ativo
Em `opac/webapp/main/views.py`
Nenhum periódico listado como descontinuado deve exibir a lista de artigos mais recentes.
N/A.
N/A.
#803 
Nenhuma.
> "Artigos recentes" - apenas periódicos ativos

- opac/webapp/templates/news/includes/collection_news_row.html
Exibe imagem dos feeds do blog SciELO, caso existam.
Em `opac/webapp/templates/news/includes/collection_news_row.html`
Com os feeds atualizados na base de dados, acessar a primeira página e as imagens já devem aparecer.
É necessário que, através do processamento, os feeds da base de dados do OPAC estejam atualizados. Para isso, é necessário que o OPAC-PROC seja atualizado com as alterações para gravar os feeds com as imagens.
#318 
Nenhuma.
> Exibe imagem dos feeds do blog SciELO

- opac/tests/test_interface_journal_home.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Exibi área "Multidisciplinar" para periódicos com 3 ou mais áreas do conhecimento
Nos seguintes módulos:
opac/webapp/main/views.py
opac/webapp/templates/journal/includes/header.html
opac/webapp/translations/en/LC_MESSAGES/messages.po
opac/webapp/translations/es/LC_MESSAGES/messages.po
opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
Acessando a página do periódico: **Anais da Academia Brasileira de Ciências**
http://localhost:8000/journal/aabc/
Não há.
https://github.com/scieloorg/opac/issues/1216
Não há.
> Exibir área Multidisciplinar para periódicos com 3 ou mais áreas do conhecimento

- opac/tests/test_interface_menu.py
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/includes/nav.html
- requirements.txt
Após a migração do SciELO.org para a nova plataforma, os links do menu do site passaram a não funcionar. Este corrige os links:
- Criando configurações para que seja possível alterar o domínio de SciELO.org e Blog
- Alterando o template para utilizar as configurações
Também foi corrigido o link de "Contato"
Em `opac/webapp/config/default.py`.
Acessando o menu do cabeçalho do novo site, todos os links para o SciELO.org e para o Blog devem funcionar
Os links do novo SciELO.org não são os mesmos da aplicação antiga. Como os links estavam hard coded no OPAC, eles passaram a não funcionar mais.
N/A.
#1245 
Nenhuma.
> Altera os links do menu, que estavam hard coded e apontando para SciELO.org antigo

- opac/webapp/main/views.py
- opac/webapp/utils/utils.py
- requirements.txt
- setup.py
Adiciona a responsabilidade de gerar os HTMLs dos artigos em tempo de execução. 
Adicionalmente foram realizadas algumas limpezas e melhorias nos códigos relacionados.
Sugiro que o revisor olhe para cada commit individualmente para que as limpezas e melhorias fiquem evidentes.
O módulo **opac/webapp/main/views.py** foi o mais afetado pela atividade.
Inicialize o servidor, com o comando **make dev_compose_up**, acesse no seu navegador e navegue pelas páginas dos documentos. Repare que o tempo de resposta agora é maior por conta da transformação XSLT realizada sob demanda. 
Os testes automáticos podem ser executados com o comando **make dev_compose_make_test**.
Decidimos adicionar a renderização do artigo em tempo de execução com o objetivo de deixar as alterações de HTMLs mais rápidas, …
> Passa a renderizar o HTML em tempo de execução

- opac/tests/test_interface_journal_home.py
- opac/tests/test_main_views.py
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Corrige o valor de citation_language para ficar correspondente a citation_title.
Também corrige código de um teste que estava quebrado, por bug inserido em #1240
- `opac/webapp/templates/article/includes/meta.html:70-80`
- `opac/webapp/templates/journal/includes/header.html`:51
```
make dev_compose_exec_shell_webapp
export OPAC_CONFIG="config/templates/testing.template"
python opac/manager.py test -p test_main_views.py
```
No próprio site, abrir a página do artigo mudando de idioma e ver o código fonte. 
Os valores de `citation_title` e `citation_language` devem alterar de acordo com o idioma do texto.
Ex: 
https://new.scielo.br/article/aa/2019.v49n1/64-70/pt
https://new.scielo.br/article/aa/2019.v49n1/64-70/es
Sobre o termo Multidisciplinar, acessar a página …
> Corrige o valor de citation_language para ficar correspondente a citation_title

- opac/webapp/admin/views.py
Altera view de periódico no Admin para que permita que seja alterado o valor do campo `is_public` (Publicado?) pela interface.
Em `opac/webapp/admin/views.py`, na classe `JournalAdminView`.
Acessando `/admin`, Catálogo > Periódico, edite qualquer periódico. Deve ser possível alterar o valor do campo `Publicado?`.
Para que seja possível criar páginas secundárias para periódicos que ainda não tem fascículos ou qualquer publicação, é necessário que os registros deles estejam disponíveis no site. Contudo, como não há documentos a serem publicados, o periódico deve permanecer despublicado. Caso haja necessidade de alteração deste status de publicação, agora será possível pela interface Admin.
N/A.
#1272 
Nenhuma.
> Altera JournalAdminView para permitir que campo is_public seja alterado

- requirements.txt
Atualiza o Packtools da versão 2.4.3 para 2.5, que corrige bugs na geração de HTMLs
Em `requirements.txt`.
Recompilar as imagens Docker do projeto, colocá-los no ar e acessar artigos XMLs.
Nenhum.
N/A
#1180 
PR scieloorg/packtools#194
> Atualiza packtools para versão 2.5

- opac/webapp/admin/custom_fields.py
- opac/webapp/admin/views.py
Abre o campo de logo do periódico para edição na interface de Admin. Assim, será possível que a produção faça atualização de logo pela interface de Admin diretamente no site.
Também efetua uma correção em `custom_fields.MediaImageUploadField`,
classe filha de `flask_admin.form.upload.ImageUploadField`, que contém
um bug na conversão de imagens para Jpeg.
Em `opac/webapp/admin/views.py`.
Para a edição da imagem:
1. Cadastrar logo de um periódico em Ativos > Imagem
2. Copiar a URL da imagem cadastrada
3. Alterar um periódico em Catálogo > Periódico
4. Colocar a URL copiada no passo 2 no campo de Logo Url e salvar.
5. Verificar na home do periódico. O Logo configurado deve aparecer.
Para a correção do bug da imagem:
1. Cadastrar uma nova imagem com formato RGBA (fundo transparente) em Ativos …
> Permite edição do campo logo_url do periódico e corrige custom field

- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/journal/includes/contact_footer.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Corrige os tooltips com uma legenda mais clara e fácil de entender
Acesse a home do periódico e posicione o mouse sobre os ícones de RSS existentes na tela.
Verifique que a mensagem está de acordo como solicitado pelo @alexxxmendonca 
Siga o passo anterior.
Nem todos os periódicos contém pres-release.
O que usei para teste foi o /journal/icse/
#1319 
Utilizei o histórico de uma conversa minha com o @jamilatta e com a @patymori onde eles me explicaram como proceder para alterar os arquivos de tradução.
> Correção de tooltips dos botões RSS na homepage do periódico

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Resolve as URLs legadas de PDFs que são localizadas pelo `assets_code`, que supostamente deveria estar presente nos fascículos. Porém, foi detectado que nem todos os fascículos tem esse dado. Quando isso acontecer, este código prevê buscar o fascículo pelos dados passados no `assets_code`.
Em `opac/webapp/controllers.py` L723.
1. Busque um fascículo que não possui o campo `assets_code`
2. Acesse um PDF de um artigo deste fascículo pela URL legada. Ex: /pdf/csp/v28n5/03.pdf
3. O PDF deve ser exibido.
Este erro foi apontado em Saúde Pública mas ocorre também na coleção Brasil
N/A
#1291 
Nenhuma.
> Resolve URLs de PDFs quebrados

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Altera o site para exibir os números de periódicos, fascículos e artigos reais da coleção, que estão de fato presentes na base de dados do site.
Pelos testes em `opac/tests/test_controller.py`
1. Acesse a página inicial do site
2. Verifique os números da coleção, que devem ser:
* Números de periódicos publicados e com status "current"
* Números de fascículos publicados
* Números de artigos publicados
Os números exibidos atualmente são os registrados no Publication Stats, que não refletem o real da base de dados do site e dependem do processamento dos dados para o site.
N/A.
#1331.
Nenhuma.
> Altera o quadro de métricas para exibir números presentes no site

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Corrige resolução de URL legada de PDFs através do `assets_code`. Este ajuste é necessário para que a correção feita anteriormente também atenda os casos onde, nos dados do fascículo, o campo `suppl_text` seja igual à uma string vazia.
Em `opac/webapp/controllers.py`, L 735
1. Busque um fascículo que tenha o campo `assets_code` igual a nulo e o `suppl_text` igual à uma string vazia
2. Acesso o PDF de um artigo deste fascículo com a URL legada, no formato `/pdf/<acrônimo do periódico>/<assets_code>/pdf_filename.pdf`
3. O PDF deve abrir sem problemas
4. Repita os passos anteriores com um fascículo que tenha o campo `suppl_text` com valor nulo
Foram encontrados casos de registros de fascículos com o campo `suppl_text` igual à uma string vazia e estes, com a busca alterada, ainda assim não …
> Corrige resolução de URL legada de PDFs

- opac/tests/test_controller.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Corrige a recuperação do PDF do artigo através da URL legada. É feita a busca através do nome do arquivo nos registros dos artigos. Caso não encontre, exibe página de erro de PDF não encontrado. Como o arquivo é salvo no SSM, que altera o nome para um nome de arquivo "seguro" (veja referências do Django), os registros de artigos no OPAC também estão com este nome diferente do original, sendo necessário que a busca também tenha este tratamento.
Em `opac/webapp/main/views.py` e depois em `opac/webapp/controllers.py`
1. Busque um fascículo que não possui o campo `assets_code`
2. Acesse um PDF de um artigo deste fascículo pela URL legada. Ex: /pdf/csp/v28n5/03.pdf
3. O PDF deve ser exibido.
4. Execute os passos anteriores com fascículos que, além do `assets_code` nulo, tenham: `suppl_text` …
> Corrige a recuperação do PDF do artigo através da URL legada

- opac/webapp/main/views.py
Altera rota para as view functions de Issue TOC, Feed TOC, artigo e PDF. Elas estabeleciam um padrão para `url_seg_issue` através de uma regex que não atende todos os url_segments possíveis. Como este é um parâmetro utilizado para busca por documentos no MongoDB que tenham exatamente este `url_segment`, caso um dado não válido seja informado, a aplicação se comporta da forma esperada, retornando 404.
Em `opac/webapp/main/views.py`, L697.
1. Localize um fascículo que fuja ao casos comuns de `url_segment` `<ano de publicação>.v<volume numérico>n<número>`. Ex: em `/grid/mioc/`, ano 1955, volume 53, número 2-3-4.
2. Acesse o fascículo e ele deve retornar corretamente
3. Acesse o feed deste Issue TOC, clicando no ícone do RSS, e ele deve abrir corretamente
4. Acesse neste Issue TOC qualquer …
> Corrige url_segment de fascículo nas rotas do Issue Toc, Feed Toc, artigo e PDF

- .travis.yml
Retira geração automática de tags no Docker Hub via TravisCI. Elas serão configuradas no próprio Docker Hub, somente quando um novo release for criado no Github.
Em `.travis.yml`
É necessário verificar após o ciclo do TravisCI que não houve disparo para gerar o Docker Hub gerar nova tag.
N/A
N/A
#1345 
Nenhuma.
> Retira geração automática de tags no Docker Hub via TravisCI

- opac/webapp/admin/views.py
Este PR tem o objetivo de listas todos os periódicos cadastrados na criação/edição das páginas secundárias, independente se o periódico está público ou não.
Também altera o campo de periódico para possibilitar a busca pelo nome, facilitando a seleção do periódico.
Em `opac/webapp/admin/views.py`, na view `PagesAdminView` 
- Acesse o admin do site o menu Pages
- Crie uma página secundária
- Vá ao campo de periódico e observe que o dropdown exibe uma caixa para digitação, que permite a busca do periódico
- Selecione um periódico, complete as demais informações e pressione Salvar
- A página deve ser cadastrada sem problemas para o periódico escolhido
- Verifique a existência de um periódico com campo `is_public` igual à `False`
- Repita os passos anteriores, selecionando um periódico com …
> Altera seleção de periódico no cadastro de páginas secundárias

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
Este pull request fixa a ordem de carregamento para as bibliotecas MathJax e Dimesions. Anteriormente as duas bibliotecas eram carregadas de forma assíncrona e na ocasião onde a Dimensions era carregada `antes` do MathJax nós tinham um problema na renderização de equações com saída em SVG.
Durante a execução desta task pude detalhar outros pontos de abordagem e metodologias para reprodução do problema no comentário https://github.com/scieloorg/opac/issues/1381#issuecomment-534748255;
- `opac/webapp/templates/article/base.html` L `56`
Pode-se testar este PR com os passos exibidos na issue https://github.com/scieloorg/opac/issues/1381 e no comentário https://github.com/scieloorg/opac/issues/1381#issuecomment-534748255;
Uma outra abordagem para solucionar o problema consistia em atualizar a …
> Fixa ordem de carregamento para o MathJax e Dimensions

- opac/webapp/config/default.py
- opac/webapp/main/views.py
Adiciona capacidade de ligar e desligar a reescrita da URL dos XMLs
Esta funcionalidade é importante para a compatibilidade do site com a
nova arquitetura, onde o XML deve ser obtido a partir do Kernel e não do
Object Store (SSM).
Foi adicionada a diretiva `OPAC_SSM_XML_URL_REWRITE`, que recebe valores
booleanos.
É importante notar que a diretiva afeta apenas a obtenção do XML; a
obtenção dos HTMLs e PDFs permanece inalterada.
`opac/webapp/config/default.py`
Defina a diretiva `OPAC_SSM_XML_URL_REWRITE` nas configurações da aplicação e perceba que: (a) quando `False`, o dado presente em `Article.xml` é utilizado sem manipulação e, (b) quando `True`, o dado é alterado de acordo com os definidos nas diretivas `OPAC_SSM_*`.
Este código é temporário e deve ser removido assim que o valor de …
> Adiciona capacidade de ligar e desligar a reescrita da URL dos XMLs

- opac/webapp/templates/issue/toc.html
Simplifica o código responsável pela exibição dos links para resumo, textos e pdfs na tabela de conteúdos de um fascículo ao iterar diretamente sobre campos específicos ao invés de no superconjunto.
Realizei uma pesquisa pelo histórico do Git e perguntei para o @jamilatta (que trabalhou no desenvolvimento do projeto desde o início) para entender a justificativa desta abordagem mas não tive sucesso. Aparentemente é um código que deixou de ser necessário e não foi refatorado devidamente.
Há apenas 1 arquivo modificado.
Pode executar a suíte de testes automatizados e testar em uma instância local.
n/a
n/a
n/a
n/a
> Simplifica a exibição dos links no TOC

- requirements.txt
Atualiza a versão do packtools para a versão 2.5.6.
No **requirements.txt**
Localmente acessando o artigo: http://0.0.0.0:8000/scielo.php?script=sci_arttext&pid=S2175-78602018000401513&lng=en&nrm=iso&tlng=en#
Necessário rodar previamente a aplicação.
Essa atualização resolve o tíquete: https://github.com/scieloorg/opac/issues/1458 
Repare como ficou o texto da citação: 
https://github.com/scieloorg/opac/issues/1458
https://github.com/scieloorg/opac/issues/1278
N/A
> Atualiza o requirements.txt com a nova versão do packtools, indiretamente resolve o tíquete: 1278 do opac

- opac/webapp/main/views.py
Resolve a necessidade de variaveis de contexto esperadas pelos templates de toc e grid.
No módulo: opac/webapp/main/views.py:747
Acessando um periódico, página da grade, exemplo: https://homolog.opac.scielo.br/grid/abb/
N/A
TK #1486
> Bug1486 - Corrige a exibição do campo ``áreas`` no cabeçalho da grade.

- requirements.txt
Esta alteração atualiza a versão do OPAC_Schema para a 2.53, que adiciona novo campo scielo_pids, usado para armazenar diferentes versões de SciELO PID.
Em `requirements.txt`
- Rodar a DAG `sync_kernel_to_website` com a versão 2.53 do OPAC_Schema, com documentos que contenham no `/front` do Kernel `scielo_pid_vn`
- Com a coleção MongoDB `article` do OPAC com o campo `scielo_pids`, acessar o site, que deve rodar sem obter erro HTTP 500.
Detalhes no ticket scieloorg/opac-airflow/issues/138
N/A
scieloorg/opac-airflow/issues/138
Especificação dos PIDs do SciELO: https://github.com/scieloorg/kernel/blob/master/docs/adr/0006-novo-pid-do-scielo.md
> Adiciona capacidade de ler diferentes versões de PIDs do SciELO.

- opac/tests/test_legacy_urls.py
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- requirements.txt
Agora as URLs antigas do site SciELO passa a retornar status 302, responde pelo idioma (tlng) e também foi atualizado a versão do **opac_schema** 2.53 -> 2.54.
opac/tests/test_legacy_urls.py
opac/tests/test_main_views.py
opac/webapp/main/views.py
requirements.txt
1. Acesse o artigo na versão em inglês [Smoking cessation during pregnancy: a population-based study](http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102019000100202&lng=pt&tlng=en)
2. Acesse o artigo na versão em português [Cessação do tabagismo na gestação: estudo de base populacional](http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102019000100202&lng=pt&tlng=pt)
3. Verifique que a tradução está sendo exibida corretamente.
Executando os teste com o comando: 
```
make dev_compose_make_test …
```
> A URL antiga do artigo no site SciELO passa a retornar HTTP status 302, atualizado a versão do opac_schema de 2.53 para 2.54.

- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Este PR resolve o problema para acessar conteúdo em URLs legadas com path `/cgi-bin/fbpe/fbtext?got=last&pid=<pid versão 1>&usr=fbpe&lng=en&seq=<seq>&nrm=iso&sss=<sss>&aut=<aut>`, que funcionavam dessa forma anteriormente ao site atual.
Para isso, foi adicionada uma _view_ para atender URL no site novo e _controller_ para buscar artigo pelo SciELO PID em diferentes versões. Em caso de sucesso na busca, o site redireciona para os detalhes do artigo no site novo.
Em `opac/webapp/main/views.py`, onde foi implementada a nova _view function_.
- Sincronize do kernel para o site algum documento que tenha o SciELO PID versão 1
- Com um artigo que possua o campo `scielo_pids`, acesse-o utilizando a URL legada no formato descrito acima. Ex: …
> Adiciona rota para primeira versão do site clássico

- opac/manager.py
Adiciona um arquivo de fixture com os PIDs dos artigo na versão em HTML e um command manager que permite atualizar os registros de articgo da aplicação com o caminho dos PDFs
A revisão pode iniciar nos seguintes arquivo: 
- opac/manager.py
- opac/fixtures/pdfs_path_file_html_version.json
Para testar manualmente é necessário uma base de dados com alguns registros para que possamos executar os seguinte commando: ```python manager.py populate_pdfs_path_html_version```
Uma tela de exemplo da saída: 
O arquivo **.json** é somente do SciELO Brasil (SCL).
#1511
- https://github.com/scieloorg/opac/issues/1495
- https://github.com/scieloorg/opac-airflow/pull/149
- https://github.com/scieloorg/opac-airflow/issues/115
> Adiciona um arquivo de fixture com os PIDs dos artigo na versão em HTML e um command manager que permite atualizar os caminhos dos registros de artigo

- opac/tests/test_controller.py
- opac/tests/test_legacy_urls.py
- opac/webapp/controllers.py
Esse PR tem como objetivo adiciona a capacidade o site novo passar a atenter URL de PDF legadas.
Com o processamento do **opac-airflow** o armazenamento das URL para os PDFs mudaram e passaram a armazenar o caminho da URL para os PDFs.
URLs que serão atendidas após essa mudança, exemplo de URL: 
http://www.scielo.br/pdf/aob/v27n2/1809-4406-aob-27-02-0080.pdf
http://www.scielo.br/pdf/aem/v63n2/2359-4292-aem-2359-3997000000120.pdf 
A alteração desse PR está basicamente no módulo **opac/webapp/controllers.py**
Para testar manualmente é possível contento na base local um registro como a imagem a baixo:
E acessando esse registro com a seguinte URL: 
http://www.scielo.br/pdf/acb/v26n4/v26n4a11.pdf
Foi necessário remover o teste **test_get_article_by_pdf_filename_returns_article_filter_result**, …
> Adiciona a capacidade de obter o PDF utilizando a URL antiga do site.

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Esse PR tem o objetivo de adicionar suporte as URLs para os **periódicos** do site clássico.
Exemplo: 
http://www.scielo.br/rae 
A idéia é que a URL http://new.scielo.br/rae seja redirecionado para http://new.scielo.br/journal/rae.
- opac/webapp/main/views.py:431
Rodar os testes: 
`make dev_compose_make_test`
Acessar em uma instância do OPAC a URL  http://new.scielo.br/ACRON
Não foi realizado qualquer validação do impacto dessa mudança nos logs de acessos coletados pelos arquivo de logs no **nginx**.
Nenhum
#1523 
Nenhum
> Adiciona suporte as URLs antigas do site classico

- opac/tests/test_utils_journal_static_page.py
- opac/webapp/main/views.py
Adiciona suporte para as seguintes URL das páginas informativas no novo site: 
- http://www.scielo.br/revistas/rpc/iaboutj.htm
- http://www.scielo.br/revistas/rpc/iedboard.htm
- http://www.scielo.br/revistas/rpc/iinstruc.htm
- http://www.scielo.br/revistas/rpc/isubscrp.htm
- opac/webapp/main/views.py:1313
- opac/tests/test_utils_journal_static_page.py
Acessando uma instância pela URL informada acima e ou rodando os testes: 
`export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test test_utils_journal_static_page`
N/A.
N/A.
#1535 
N/A.
> Adicionar suporte as URLs das páginas informativas

- opac/tests/test_main_views.py
- opac/webapp/templates/article/includes/modal/download.html
Corrigi o caminho para o PDF no modal da página do artigo
opac/tests/test_main_views.py:1431
opac/webapp/templates/article/includes/modal/download.html:20
Acessando uma instância do site com o PR aplicado e verificar se as URLs para os PDFs estão considerando o idioma. 
N/A
#1531 
N/A
> Corrigi o caminho para os PDFs no modal.

- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/article/includes/modal/download.html
- opac/webapp/templates/article/includes/recent_articles_row.html
- opac/webapp/templates/issue/toc.html
Adiciona suporte à nova URL canônica dos documentos e PDFs, com o formato
`/article/:journal_acron/:article_pid_v3` e `/pdf/:journal_acron/:article_pid_v3`, respectivamente. As URLs nos formatos anteriores passam a redirecionar o cliente para as novas.
Sugiro revisar os _commits_ individualmente e na ordem de execução.
Inicialize uma instância local e navegue pelo site, percebendo as URLs para documentos HTML e PDF. Verifique também as URLs legadas.
n/a
n/a
#1547 
n/a
> Altera padrão da URL dos documentos

- opac/webapp/config/templates/testing.template
Este PR resolve o problema dos testes unitários utilizarem a mesma base de dados da aplicação no MongoDB. Foi alterado o valor da variável `config.MONGODB_NAME` para utilizar um nome fixo de teste, evitando a utilização da base de dados configurada na variável de ambiente `OPAC_MONGODB_NAME`, nome da base real usada pelo site.
Em `opac/webapp/config/templates/testing.template`
- Rode o comando `make test`.
- Observe no MongoDB que o uma base com nome `opac_test` está sendo usada durante os testes unitários e que a base `opac` permanece como estava.
- Rode o comando `make dev_compose_make_test` para executar os testes unitários no Docker.
- Observe o mesmo efeito descrito no passo 2.
Fiz experimentos com o `mongomock` e alterações no código de teste para tentar outros tipos de abordagem, …
> Altera template de config de teste p/ evitar uso da base de produção

- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
Seguindo a mesma alteração realizada na página do sumário do fascículo [baf5ac28311ee3174ac09e679d4b165bb750dbb0],
agora a alteração foi realizada na página do artigo.
n/a
Caso seja instalado diretamente na máquina local será necessário executar `make compile_messages` após aplicar o patch e antes de executar o servidor de aplicação.
n/a
n/a
#859 
n/a
> Altera tradução de *sumário* na página do artigo

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Modifica a rota para a página inicial do periódico de /journal/acron para /j/acron.
por commits
Usando os testes unitários conforme informados no README
Ou acessando a página de um periódico com o padrão novo e com o padrão antigo percebendo que há redirecionamento
n/a
n/a
Resolve parte de #1548 
n/a
> Modifica a rota para a página inicial do periódico de /journal/acron para /j/acron

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Substitui a rota /grid/acron por /j/acron/grid que corresponde à grade de fascículos
Por commits
- Rodando os testes conforme o README
- Acessando a página de qualquer periódico e depois da grade de fascículos, notar que o padrão de url é  /j/acron/grid
- Acessando a página da grade de fascículos de qualquer periódico:
- /grid/acron, notar que redireciona
- /j/acron/grid notar que está acessível
n/a
n/a
Resolve parcialmente #1564 
n/a
> Substitui a rota /grid/acron por /j/acron/grid

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Cria nova rota para o sumário (de /toc/acron/issue_url_seg para /j/acron/i/issue_url_seg
Por commits
Acessar a página de todos os fascículos e acessar qualquer fascículo.
Notar o novo padrão de rota.
Com o padrão antigo, verificar que é redirecionado.
Também é possível executar os testes de unidade
n/a
n/a
Resolve parte de #1548
n/a
> Cria nova rota para o sumário (de /toc/acron/issue_url_seg para /j/acron/i/issue_url_seg

- Dockerfile
- opac/tests/test_interface_TOC.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/issue/grid.html
- opac/webapp/templates/issue/toc.html
- requirements.txt
Cria uma nova rota `/j/<acron>/aop` no lugar de:
- `/toc/<acron>/2019.nahead`
- `/j/<acron>/i/2019.nahead`
- `/scielo.php?script=sci_issuetoc&pid=0101-280020200050&lng=en&nrm=iso`
e redireciona as rotas antigas para a nova
por commits
com testes de unidade
`python opac/manager.py test -p test_main_views.py`
`python opac/manager.py test -p test_interface_TOC.py`
Ou acessando periódicos que contenha aop, verificando a rota nova e os redirecionamentos.
- 0004-274920200050 abo
- 0004-280320200050 ag
- 0004-282x20200050 anp
- 0006-870520200050 brag
- 0066-782x20200050 abc
- 0100-398420200050 rb
- 0101-206120200050 cta
- 0101-280020200050 jbn
- 0102-763820200050 rbccv
- 0103-218620200050 eh
- 0104-403620200050 ensaio
- 1413-415220200050 esa
- 1414-462x20200050 cadsc
- 1516-318020200050 spmj
- …
> Cria uma rota nova para os sumários de aop 

- opac/tests/test_legacy_urls.py
- opac/webapp/main/views.py
Esse PR tem como objetivo alterar o status code das URLs legadas para 301.
É possível revisar esse PR olhando os seguintes arquivos
- opac/tests/test_legacy_urls.py
- opac/webapp/main/views.py
Iniciando a aplicação com Docker:
```
make dev_compose_dev 
```
Acessando as seguintes páginas: 
- /scielo.php?script=sci_serial&pid=0066-782X&lng=en&nrm=iso
- /scielo.php?script=sci_issuetoc&pid=0066-782X20200002&lng=en&nrm=iso
- /scielo.php?script=sci_issues&pid=0066-782X&lng=en&nrm=iso
Foram adicionado novos testes no módulo de testes:
```
make dev_compose_make_test
```
N/A
N/A
Tíquete referente a esse PR: https://github.com/scieloorg/opac/issues/1568
N/A
> Altera as URLs legadas para retorna HTTP status code 301.

- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/_dont_display_full_text.html
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/article/includes/modal/download.html
- opac/webapp/templates/article/includes/recent_articles_row.html
- opac/webapp/templates/issue/toc.html
Altera o padrão de URL dos documentos em HTML e PDF, conforme descrito em #1580. As URLs para HTML e PDF foram unificadas e o argumento `format`, da querystring, passou a ser utilizado para especificar o formato desejado. 
N/A
1. Inicie uma instância povoada com documentos em HTML e PDF.
2. Acesse o sumário de um periódico e verifique que os links para as versões HTML e PDF dos documentos estão conforme o padrão `/j/:acron/a/:id_doc?format=:format&lang=:lang`, sendo opcionais todos os argumentos da querystring.
3. Acesse a página de um periódico e em seguida clique no ícone de RSS, no canto inferior direito da tela e no canto superior direito da "moldura" aonde são apresentados os conteúdos do periódico, e verifique que as URLs dos documentos estão conforme o mesmo padrão descrito …
> Altera o padrão de URL dos documentos

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Este pull request modifica os _status_ de retorno para `500` quando acontece alguma falha de integração entre o site o kernel e/ou minio. Antes o status de retorno era o `404` indicando que aquele recurso não existia, isso obviamente era um erro.
- Pelo arquivo `opac/webapp/main/views.py`
Para testar este PR manualmente, deve-se:
- Suba uma instância funcional do site integrado com o Kernel e Minio;
- Navegue entre os arquivos para garantir que estão abrindo;
- Desligue o serviço do Kernel ou o minio;
- Tente navegar entre os artigos ou acessar os pdfs;
- Observe que o site deve informar erros 500 em vez de 400.
Talvez devêssemos implementar rotinas para realizar retentativas de acesso  aos objetos do kernel e do minio. Isso poderia minimizar erros de apresentação para os clientes.
N/A …
> Alterar o código de status para 500 quando um erro de integração ocorre

- opac/webapp/main/views.py
Corrige um defeito inserido pelo PR #1669, na filtragem dos documentos pelo título da seção
por commits
1. Acesse a página https://new.scielo.br/j/brjp/aop
2. Clique no link "ORIGINAL ARTICLE"
3. Observe os documentos foram filtrados pelo título da seção "ORIGINAL ARTICLE"
Isso acontecia a qualquer fascículo.
Não consegui testar em um AOP porque a minha base local não há. O acesso à base de produção está instável.
n/a
#1677
n/a
> Corrige a filtragem de documentos pelo título da seção

- opac/tests/test_legacy_urls.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Esse PR adiciona a capacidade de resolver as URLs do legado considerando todas as versões de PID.
É possível revisar esse PR, verificando as alterações nos seguintes módulo: 
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Ou nos novos testes adicionados no módulo: 
- opac/tests/test_legacy_urls.py
Para testar manualmente é necessária uma instância do OPAC com dados e acessar as seguintes URLs com conteúdo.
https://new.scielo.br/scielo.php?script=sci_arttext&pid={PID} 
https://new.scielo.br/scielo.php?script=sci_pdf&pid={PID}
Sendo que para esse caso, um teste mais fiel seria que o PIDs utilizados estejam no campo `scielo_pids` do **opac_schema**.
N/A
N/A
Tíquete referente a esse PR: https://github.com/scieloorg/opac/issues/1684
N/A
> Altera as rotas legadas para considerar todos os PIDS.

- opac/tests/test_controller.py
- opac/tests/test_legacy_urls.py
- opac/webapp/controllers.py
Esse PR tem o objetivo de ajustar a obtenção do PDF para URLs legadas do site, exemplo: https://www.scielo.br/pdf/abb/v33n2/0102-3306-abb-0102-33062018abb0352.pdf
É possível revisar esse PR da seguinte forma: 
Olhando os módulos:
- opac/webapp/controllers.py
- opac/tests/test_controller.py
- opac/tests/test_legacy_urls.py
Através dos testes:
``export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test -p "test_controller.py" -f``
ou 
``make dev_compose_make_test``
Com uma instância local e acessando URL antigas para PDF no site novo exemplo: 
http://localhost:8000/pdf/anaismp/v28/1982-0267-anaismp-28-d1e9.pdf
http://localhost:8000/pdf/alea/v20n1/1807-0299-alea-20-01-17.pdf
http://localhost:8000/pdf/esa/2017nahead/1809-4457-esa-s1413-41522017129981.pdf
Para …
> Corrige a obtenção de PDF nas URL antigas do site.

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/meta.html
Corrige o endereço do pdf que é atribuído na tag `<meta name="citation_pdf_url"/>`
por commits
Acessar a página do artigo e verificar que o valor do atributo `content=` está correto. Veja #1666
n/a
n/a
#1666
n/a
> Corrige o endereço do pdf que é atribuído na tag `<meta name="citation_pdf_url"/>`

- opac/webapp/templates/issue/grid.html
Apresenta `s/v` para ausência de volume no _grid_
por commits
Veja o #1327
n/a
#1327
n/a
> Apresenta `s/v` para ausência de volume no _grid_

- requirements.txt
Atualiza a versão do Pillow para ficar compatível com packtools==2.6.8
https://travis-ci.org/github/scieloorg/opac/builds/746844320
```
ERROR: Cannot install -r /app/requirements.txt (line 45) and Pillow==5.2.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested Pillow==5.2.0
packtools 2.6.8rc20201201 depends on Pillow~=6.2
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
> Atualiza a versão do Pillow para ficar compatível com packtools==2.6.8

- opac/tests/fixtures/document.xml
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Este PR disponibiliza os documentos em XMLs SciELO PS retornados pelo Kernel, acessando URLs com formato `/j/<acron>/a/<PID v3>/?format=xml`. Também adiciona esta URL nos metadados do documento em formato HTML.
Commit 2488edc.
1. Obtenha o PID v3 de um documento presente em instância do novo site
2. Acesse a URL `<endereço do site>/j/<acrônimo do periódico>/a/<PID v3>/?format=xml`
3. Verifique se o XML do documento é renderizado
3. Acesse a URL `<endereço do site>/j/<acrônimo do periódico>/a/<PID v3>`. Caso o acesso seja feito via navegador, abra o código fonte da página.
4. Verifique a presença da tag:
```<meta content="https://enderecodosite/j/acron/a/pid-v3-do-documento/?format=xml" name="citation_xml_url">```
.
.
Closes #1667.
.
> Disponibiliza publicamente os XMLs SciELO PS dos documentos

- requirements.txt
Este PR atualiza a versão do Packtools que gera o modal das tags `fig` mesmo sem o atributo `id`, possibilitando visualizar a versão em tamanho original das imagens.
Em `requirements.txt`
1. Obtenha um documento em que o XML contenha a tag `fig` sem atributo `id`, como o exemplo abaixo:
2. Acesse a página do artigo
3. Verifique se a imagem do thumbnail é exibida no modal ao clicar nela.
.
.
#1654.
.
> Atualiza versão do packtools para exibir imagem em tamanho original com tag fig sem id

- requirements.txt
Este PR atualiza a versão do Packtools para `2.6.10` e renderizar os artigos HTML com todos os resumos do documento, independente de idioma.
Em `requirements.txt`.
1. Instale as dependências da app com `pip install -r requirements.txt`, caso esteja usando uma Virtualenv, ou execute o `make dev_compose_build && make dev_compose_up` para testar no Docker.
2. Acesse a página de um artigo na instância do site
3. Verifique se todos os resumos são exibidos, independente do idioma do texto atual.
.
.
https://github.com/scieloorg/packtools/issues/215
.
> Atualiza versão do packtools p/ resolver exibição de resumos do artigo

- requirements.txt
Este PR permite que a preferência de leitura seja definida via URI de conexão com o MongoDB, informada na variável `OPAC_MONGODB_HOST`, através do parâmetro `readPreference`.
A versão 0.15.3 do MongoEngine tem um bug que não faz o parser da URI de conexão corretamente, não configurando readPreference informado e mantendo a preferência de leitura para o primário.
Commit bee3856.
- Configure a variável `OPAC_MONGODB_HOST` com uma URI de conexão com uma lista de nodes MongoDB, passando o parâmetro `readPreference` diferente de `primary`. As opções possíveis estão na [documentação do MongoDB](https://docs.mongodb.com/manual/reference/connection-string/#urioption.readPreference)
- Suba a instância do OPAC
- Acesse o shell do `manager.py` com a linha de comando `cd opac && python manager.py …
> Corrige configuração de conexão com MongoDB via URI

- docker-compose-dev.yml
- docker-compose.yml
- opac/webapp/__init__.py
- opac/webapp/config/default.py
Este _pull request_ torna possível a configuração do nível de log da aplicação a partir da variável de ambiente `OPAC_LOG_LEVEL`. Melhora leitura de logs para a aplicação em produção.
- Pelo arquivo `opac/webapp/config/default.py`
- Depois `opac/webapp/__init__.py`
- Configure a variável `OPAC_LOG_LEVEL` no arquivo de `docker-compose`;
- Acesse páginas como as de artigos;
- Habilite o `APM`;
- Mude o nível de log para `DEBUG` e verifique que o `APM` imprime mensagens de `DEBUG`;
- Mude o nível de log para `ERROR` e verifique que o `APM` não imprime as mensagens de `DEBUG`;
- Desconecte da VPN;
- Verifique que o `APM` imprime mensagens de erro de conexão;
N/A
N/A
close #1781 
N/A
> Permite a configuração do nível de log da aplicação e suas dependências

- opac/tests/test_controller.py
- opac/tests/test_interface_journal_home.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/detail.html
- requirements.txt
Este PR exibe o índice e a mediana H5 do Google Scholar,  utilizando a lib https://github.com/scieloorg/scieloh5m5.
Commit 028011b.
1. Suba uma instância do projeto, conectando-a a uma base de dados MongoDB contendo periódicos da coleção BR
2. Acesse a home de periódicos
3. Observe que as métricas do Google Scholar são exibidas, como no print de tela em anexo [1]
[1] - Home do periódico com as métricas do Google Scholar
Fix #1796 
.
> Ajusta exibição do índice e a mediana H5 do Google Scholar na home do periódico

- opac/tests/test_controller.py
- opac/tests/test_interface_TOC.py
- opac/tests/test_legacy_urls.py
- opac/tests/test_main_views.py
- opac/tests/test_main_views_abstract.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/issue/toc.html
- requirements.txt
Apresenta os links dos resumos no padrão `/j/<acron>/a/<docid>/abstract/?lang=<lang>` no sumário
pelo commit https://github.com/scieloorg/opac/commit/c0cd3c25fcddbb1de4468e371374cb95d95ad295
Acesse o sumário qualquer e confira os links para os resumos
n/a
n/a
#1762, #1730
n/a
> Apresenta os links dos resumos no padrão `/j/<acron>/a/<docid>/abstract/?lang=<lang>` no sumário

- opac/tests/test_controller.py
- opac/tests/test_interface_menu.py
- opac/tests/utils.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/article/includes/levelMenu_layout_lg.html
- opac/webapp/templates/article/includes/levelMenu_layout_md.html
- opac/webapp/templates/article/includes/levelMenu_layout_sm.html
Trata da navegação entre os resumos (próximo e anterior). Levando em consideração:
- Nem todos os documentos tem resumos, então a lista a ser navegada, tem que conter somente os documentos com resumos
- Foi refatorado a identificação de "previous" e "next" para obter melhor desempenho. O código anterior sempre identificava o anterior e o próximo fazendo uma consulta ao banco. No código novo, a consulta não é feita sempre. Só é feita caso o usuário comece a navegar pelo próximo ou anterior (parâmetro `goto`).  É uma aborgadem parecida com o que foi feita com `issue_toc`. 
por commits
Acesse um documento e/ou um resumo e navegue pelo anterior e o próximo
A aplicação tenta evitar que o usuário navegue por próximo e anterior e receba uma mensagem de erro de recurso não encontrado. Mas a …
> Trata da navegação entre os resumos (próximo e anterior)

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Remove o filtro para obter os resumos na consulta
Filtra após a consulta, considerando se o campo `abstracts` tem o conteúdo `text` preenchido.
Usar o filtro `abstract` falha quando o documento não tem resumo no idioma original. 
Usar o filtro  para `abstracts` pode trazer documentos campo `abstracts` estão incorretos, como apresentado na imagem:
por commits
Acesse um documento e/ou um resumo e navegue pelo anterior e o próximo, verificando se a lista contém os resumos esperados.
n/a
n/a
https://github.com/scieloorg/opac/issues/1762
https://github.com/scieloorg/opac/pull/1816
n/a
> Remove o filtro para obter os resumos na consulta. Filtra após a consulta

- requirements.txt
Atualiza a versão do packtools para 2.6.12 que
- corrige transformações de `graphic` e `inline-graphic`
.
Veja a seção `como reproduzir o problema`
https://github.com/scieloorg/packtools/issues/248
https://github.com/scieloorg/packtools/issues/250
n/a
n/a
https://github.com/scieloorg/packtools/issues/248
https://github.com/scieloorg/packtools/issues/250
n/a
> Atualiza a versão do packtools para 2.6.12

- opac/webapp/controllers.py
- requirements.dev.txt
Este PR altera a busca de `Article` no MongoDB na consulta a um documento, feita ao acessar um artigo.
Usando o [pyinstrument](https://github.com/joerick/pyinstrument#pyinstrument), foi possível observar uma diferença de até 400ms a menos com a consulta, conforme mostram as imagens [1] e [2]. O teste foi feito acessando o PDF de um artigo, com e sem a alteração.
Commit 9b68cab.
- Para visualizar o resultado, é necessário garantir que a instância foco do teste não esteja usando o Redis ou que o cache seja limpo para cada requisição
- Execute `pip install -r requirements.dev.txt` ou recompile o contêiner do opac_webapp.
- Adicione o seguinte código em `opac/webapp/main/views.py`:
```
from pyinstrument import Profiler
@main.before_app_request
def before_request():
if "profile" in …
```
> Altera consulta de artigo no banco de dados p/ melhorar a performance

- opac/webapp/main/views.py
- requirements.txt
Remove a necessidade de avaliar o **HTML** com **BeautifulSoup**, para que tenhamos ganho de performe no acesso à página do artigo.
Verifique a **view.py** a partir da linha: **1030**
Para teste manual da alteração sugiro utilizar o utilitário desenvolvido pelo @joffilyfe no seguinte link: https://github.com/joffilyfe/scielo-replay-http-traffic
Ofereço para esse teste alguns insumos que segue:
- **Commando para execução**: time python main.py log_apache/apache.log http://0.0.0.0:5000 --connections 10 --dont-wait-until-request-time --output-file "resultado_stress/10-conexoes.csv"
- Em anexo contém a pasta log_apache com os arquivos necessários para execução do comando anterior
[log_apache.zip](https://github.com/scieloorg/opac/files/6244859/log_apache.zip)
#1812
> Remove a necessidade de avaliar o HTML com BeautifulSoup no acesso a página do artigo.

- opac/webapp/controllers.py
- opac/webapp/main/views.py
Adiciona rota /api/v1/counter_dict/ para gerar dicionário de PIDs e outros atributos para aplicação COUNTER.
Apenas dois arquivos foram modificados. Um controlador foi adicionado para obter artigos com base nos campos created e updated de objetos Article. Uma rota (/api/v1/counter_dict ou /api/v1/counter_dict/YYYY-MM-DD) foi adicionada para obter dados obtidos por meio do controlador.
A quantidade de dados é limitada a 30 dias, a partir da data indicada e percorrendo o tempo no sentido do passado. É importante averiguar se a obtenção de dados, por meio do método adicionado ao controlador, é ótima (otimizada, eficiente, eficaz, etc). 
É preciso ter uma base mongodb com dados do OPAC São necessários, pelo menos, registros das coleções collection, journal, issue e article. Deve-se subir uma …
> Adiciona rota para gerar dicionário de PIDs e outros atributos para aplicação COUNTER

- README.rst
Adiciona a capacidade do desenvolvedor popular o banco de dados local com 4 periódicos. 
Lendo as alterações no **README.rst** 
Realizando de fato os novos passos para popular o banco de dados.
Ainda é necessário o uso da **VPN SciELO** para visualizar a página do artigo.
Referente a atividade: #1864
> Adiciona no README o procedimento para rodar uma instância do OPAC com dados populado a partir de fixtures disponibilizadas pelo SciELO no minio.

- gulpfile.js
- opac/webapp/static/less/article.less
- opac/webapp/templates/article/includes/levelMenu_pdf.html
- package.json
Corrige o gulpfile.js, responsável por gerar os arquivos css e js minificados.
Atualiza o package.json, responsável por instalar as dependências necessárias para rodar o gulpfile.js
Atualiza o arquivo article.less adicionando classes que corrigem posicionamento de alguns elementos de interface quando em dispositivos móveis.
Atualiza o arquivo levelMenu_pdf exibindo um dropdown mesmo quando houver apenas uma possibilidade de idioma em arquivos PDF. Ao abrir o dropdown a opção de idioma é exibida.
1 - Baixe a atualização
2 - rode um npm install para instalar as dependencias necessárias pra rodar o gulpfile e gerar os arquivos css e js minificados
3 - na raiz do projeto, rode o comando "gulp". Esse comando vai gerar todos os arquivos css e js atualizados com base nos arquivos .less e js.
4 - …
> Alinhamento dos botões resumo, texto e pdf na tela do artigo

- opac/webapp/templates/base.html
Atualização do código javascript para registrar dados no GA googleanalytics
por commits
Crie uma variável de ambiente chamada GA_TRACKING_CODE com um valor qualquer. 
1. Suba o website.
2. Abra uma página qualquer.
3. Abra seu código fonte.
4. Procure pelo código "VALORQQ".
5. Você deve encontrar algo como:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=VALORQQ"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'VALORQQ');
</script>
```
OBS.: certifique que a variável de ambiente `OPAC_DEBUG_MODE=False`
n/a
#1902
n/a
> Atualização do código javascript para registrar dados no GA googleanalytics

- README.rst
- opac/webapp/config/default.py
- opac/webapp/templates/collection/base.html
Deixa a mensagem no topo da home configurável e com possibilidade de acrescentar um link para a versão anterior do website.
por commits
configurando as variáveis como variáveis de ambiente, subindo a aplicação, e olhando a página principal. 
Há "duas" variáveis configuráveis:
- texto que corresponde a "New portal may contain inaccuracies", pode ser qualquer mensagem ou nenhuma mensagem.
```
ALERT_MSG_PT=Novo portal pode conter incorreções
ALERT_MSG_EN=New portal may contain inaccuracies 
ALERT_MSG_ES=Nuevo portal puede contener incorrecciones
```
- exclusivamente o endereço do website anterior
``` 
PREVIOUS_WEBSITE_URI=https://old.scielo.br
```
**AMBAS CONFIGURADAS**
**TEXTO CONFIGURADO**
**LINK CONFIGURADO**
**NENHUM**
#1895
n/a
> Deixa a mensagem no topo da home configurável e com possibilidade de acrescentar um link para a versão anterior do website.

- Dockerfile
- opac/webapp/static/robots.txt
Faz com que por padrão o Gunicorn use workers do tipo gthread, com 4 threads por worker. Essa mudança visa fazer com que cada worker seja capaz de atender mais requisições concorrentes sem aumentar significativamente o consumo de recursos, em específico de memória.
Além disso, este _pull request_ também altera o arquivo `robots.txt` de forma que fique mais permissivo por
padrão.
Basta subir localmente uma instância da aplicação. Durante a inicialização, o Gunicorn imprime na tela qual tipo de worker está sendo utilizado, observe se `gthreads` é escrito.
Para testar o `robots.txt`, acesse 0.0.0.0:8000/robots.txt e veja se ele está como o arquivo enviado neste PR.
n/a
n/a
n/a
n/a
> Altera worker do Gunicorn e robots.txt

- opac/webapp/templates/collection/index.html
Remove a faixa de números (fascículos) da página inicial
por commits
Acessando a página inicial e verificando a ausência da faixa de números
n/a
antes:
depois:
Indique uma issue ao qual o pull request faz relacionamento.
n/a
> Remove a faixa de números (fascículos) da página inicial

- opac/webapp/main/views.py
- opac/webapp/templates/collection/index.html
Remove métricas de "Números" da faixa "Brasil em números | Métricas"
por commits
ver #1908
n/a
antes:
#1908 
n/a
> Remove métricas de "Números" da faixa "Brasil em números | Métricas"

- opac/tests/test_controller.py
- opac/tests/test_legacy_urls.py
- opac/tests/test_main_views.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Resolve a indisponibilidade dos PDFs de aop e daqueles que tem idioma no nome do arquivo.
Arquivos no padrão `/pdf/acron/volumenumero/arquivo.pdf`. 
por commits
Acessando pdfs no padrão `/pdf/acron/volumenumero/arquivo.pdf` de aop e com idioma como prefixo, por exemplo:
http://www.scielo.br/pdf/rlae/v29/es_0104-1169-rlae-29-e3395.pdf
https://www.scielo.br/pdf/cta/2020nahead/0101-2061-cta-fst21020.pdf
- Questão do aop é que mudamos a forma de modelar. Há apenas 1 registro de aop. Não há mais 1 aop por ano.
- Falta de adequação dos nomes dos pdf que tem idioma no nome do arquivo. No pacote SPS o idioma é sufixo enquanto no site era prefixo.
n/a
#1921
n/a
> Resolve a indisponibilidade dos PDFs de aop e daqueles que tem idioma no nome do arquivo 

- opac/tests/test_utils.py
- opac/tests/test_utils_page_migration.py
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/utils/page_migration.py
Corrige "migração de páginas" para conseguir salvar páginas informativas. A "migração de páginas informativas" corrige URI e migra imagens e arquivos do site anterior para o novo.
por commits
Ver como simular o erro em #1935
O erro ocorria ao tentar baixar a imagem `https://www.scielo.br/media/images/capes_jvatitd.png` do site novo como se fosse do site anterior.
n/a
#1935
n/a
> Corrige "migração de páginas" para conseguir salvar páginas informativas

- opac/webapp/controllers.py
- opac/webapp/main/views.py
Adiciona paginação em rota api/v1/counter_dict. Resolve bug #1953.
Por commits.
1. Tenha uma instância do OPAC
2. Tenha uma base de dados mongo/OPAC povoada com artigos e demais insumos
3. Acesse a rota http://0.0.0.0:8000/api/v1/counter_dict?end_date=2021-03-30
4. Verifique os parâmetros de paginação adicionado no JSON apresentado
5. Verifique que o número de documentos é limitado ao parâmetro "limit"
6. Acesse uma página válida, tam como http://0.0.0.0:8000/api/v1/counter_dict?end_date=2021-03-30&page=2
A rota api/v1/counter_dict existe para disponibilizar insumos necessários ao cálculo de métricas COUNTER no contexto do novo site Brasil. São retornados dados dos 30 dias prévios ao parâmetro end_date - esse é um requisito da aplicação COUNTER.
_Trecho inicial de uma requisição_
_Trecho …
> Adiciona paginação em rota api/v1/counter_dict

- requirements.txt
Atualizar a versão do packtools para v2.7.1 para corrigir questões do resumo
- garantir que apresentação de highlights tem que ser antes dos demais resumos
- os highlights não tem palavras-chaves
- o primeiro resumo está com as palavras-chaves em idioma incorreto (isso só ocorre nos XML cujo grupo de palavras chaves está em ordem diferente da dos resumos)
- artigo não tem resumo, mas apresenta o título "Abstract" (isso ocorre porque no XML tem a tag <abstract/> vazia)
n/a
https://github.com/scieloorg/packtools/pull/266
n/a
n/a
https://github.com/scieloorg/packtools/issues/265
https://github.com/scieloorg/packtools/issues/217
n/a
> Atualizar a versão do packtools para v2.7.1

- opac/tests/test_controller.py
- opac/tests/test_legacy_urls.py
- opac/tests/test_main_views.py
- opac/tests/test_main_views_abstract.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Recupera artigo usando também o campo `scielo_pids.other`, que pode conter qualquer tipo de pid.
por commits
Acessando uma página de artigo seja pelo pid v1, v2 ou v3 e que estes valores estejam no campo `scielo_pids.other` no lugar de estar em `pid`, `aop_pid`
n/a
n/a
https://github.com/scieloorg/opac-airflow/issues/287
```python
from mongoengine import connect
conn = connect(host="mongodb://127.0.0.1:27017/meu_opac")
from opac_schema.v1.models import (
Journal,
Issue,
Article,
Collection,
News,
Pages,
PressRelease,
Sponsor)
a = Article.objects(authors__in=["CASTRO, RODRIGO B."])
a = Article.objects(scielo_pids__v2__contains='S1')
scielo_pid = 'S0001-37652020000300725'
a = Article.objects(Q(pid=scielo_pid) | Q(scielo_pids__v1=scielo_pid) | Q(scielo_pids__other__in=scielo_pid)).first() …
```
> Recupera artigo usando também o campo `scielo_pids.other`

- requirements.txt
Atualiza a versão de packtools para 2.7.2 que apresenta o `<xref><italic>et al</italic></xref>`
n/a
Acessando https://www.scielo.br/j/nau/a/4xc3jLsVH6cG6bjMRGpZY3v
n/a
n/a
https://github.com/scieloorg/packtools/issues/267
n/a
> Atualiza a versão de packtools para 2.7.2 que apresenta o `<xref><italic>et al</italic></xref>`

- opac/tests/test_interface_journal_home.py
- opac/tests/test_main_views.py
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/base.html
- opac/webapp/templates/issue/base.html
- opac/webapp/templates/issue/includes/meta.html
- opac/webapp/templates/journal/base.html
- opac/webapp/templates/journal/includes/meta.html
Adiciona no cabeçalho das páginas que contém compartilhamento tags "**Open Graph**" objetivando um compartilhamento mais elegante e aderente.
É possível testar esse PR olhando os commit e rodando os teste: ```export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test```
Acessando a página do (periódico, fascículo ou artigo) e clicando no ícone de compartilhamento do facebook ou twitter.
Não foi possível realizar testes de compartilhamento com o facebook e o twitter utilizando a novas tags já que a aplicação precisa que esteja com uma URL pública.
Sugiro que após aprovado esse PR possamos utilizar o ambiente de homologação para esse teste.
Ferramenta do facebook para teste:  https://developers.facebook.com/tools/debug/
Esse PR resolve o tíquete #1950.
Veja as …
> Tk1950 - Compartilhamento.

- opac/webapp/controllers.py
Otimiza método get_articles_by_date_range. A alteração consiste em remover da consulta o campo `create`. O campo `update` é mantido na consulta.
Por commit.
1. Ter instância do opac instalada
2. Acessar rota api/v1/counter_dict e verificar retorno de dicionário de dados
A ideia do PR é melhorar o tempo de consulta à base mongodb.
N/A
#1988
N/A
> Simplifica consulta a artigos com base em período de datas

- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/includes/metric_modal.html
Realiza um ajuste de segurança para garantir que o badge do plumx funcione sem bloqueio de javascript de terceiros.
Olhando os commit e avaliando de forma visual a imagem do badge.
Acessando o site e clicando no link de métricas no canto inferior esquerdo:
#1131 
Para resolução dessa atividade foi necessário estudar sobre os seguinte assunto nos diferentes links: 
**Content-Type**: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
**Nosniff:** https://fetch.spec.whatwg.org/#should-response-to-request-be-blocked-due-to-nosniff?
Google sobre o erro: **foi bloqueado devido ao tipo mime (“text/html”) não coincidir com (x-content-type-options: nosniff)**
> Tk1131 - Ajuste no badge do Plumx

- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/base.html
- opac/webapp/templates/issue/includes/meta.html
- opac/webapp/templates/journal/includes/meta.html
Remove um content block que produz duplicidade de tags share.
Por commit.
Subindo a aplicação localmente é possível verificar no código HTML que não existe mas duplicidade.
Esse bug foi introduzido no PR: https://github.com/scieloorg/opac/pull/1987
#1995 
N/A
> Remove um content block que produz duplicidade de tags share.

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Adiciona o idioma original na URL dos XML para Google.
Por commit.
Acessando uma página de uma artigo e verificando no HTML se exite uma metatag ``citation_xml_url``
n/a
n/a
Não houve tíquete para essa atividade.
n/a
> Adiciona o idioma original na URL dos XML para Google.

- opac/webapp/templates/article/includes/meta.html
Garante que não exista tags duplicadas de nome de autor aos alternarmos entre authors e auhtors_meta.
Por commit.
Iniciando uma instância da aplicação acessando artigos que contém e não contém o campo **authors_meta** e **authors**
Essa atividade garante que no momento que exista o **authors_meta** ele seja utilizado, caso contrário será utilizado o campo **authors**. 
Também garante que somente seja criado as tags **citation_orcid** e **citation_affiliation** se existirem na entidade do **authors_meta**.
N/A
Esse PR é uma melhoria dos tíquetes: #1951  e #1952 
N/A
> Garante que não exista tags duplicadas de nome de autor aos alternarmos entre authors e auhtors_meta.

- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/index.html
Adiciona a capacidade de ligar e desligar a faixa de métricas no site.
Por commit. 
Iniciando o site e visualizando que a faixa está desativada.
A partir do momento que é desligado a exibição da faixa, não será mais consultado a tabela de coleção do site.
#2007
N/A
> Adiciona a capacidade de ligar e desligar a faixa de métricas no site.

- gulpfile.js
corrige o arquivo gulpfile.js
Foi adicionado na função processScieloArticleLess o comando concat, que é reponsável por agrupar mais de um arquivo de entrada e transformar em um único arquivo de saída.
Na linha de comando, rode o comando "gulp"
Os arquivos .css e .css.map serão criados. Perceba que o arquivo scielo-bundle.css contém todas as classes que estão nos arquivos:
scielo-bundle.less
style.less
jquery.typeahead.less
Siga os passos citados acima e teste na aplicação.
Não.
Perceba o css do autocomplete. Está correto.
Perceba o resumo não é mais exibido:
#2031 
-
> correcao na geracao do scielo-bundle.css 

- opac/webapp/main/views.py
Disponibiliza o resumo no idioma correspondente em uma página de resumos para resumos proveniente de marcação HTML
por commits
Acesse o sumário de um periódico ingressado como HTML
O campo `article.xml` não deve estar preenchido.
Acesse o resumo do documento ingressado como HTML.
n/a
#2045
n/a
> Disponibiliza o resumo no idioma correspondente em uma página de resumos para resumos proveniente de marcação HTML

- opac/manager.py
- opac/tests/test_main_views.py
- opac/webapp/config/default.py
- opac/webapp/config/templates/testing.template
- opac/webapp/main/views.py
Adiciona um parâmetro de configuração para forçar o uso de **https** na formação das meta_tags do google.
Meta tags do google: https://developers.google.com/search/docs/advanced/crawling/special-tags
Por commit e rodando os testes.
É possível acessando a página de um artigo e verificando que a formação para URL do pdf e xml nos meta_tags: 
```
citation_pdf_url
e
citation_xml_url
```
Estão com https na formação da URL.
Essa alteração foi realizada devido um comportamento não desejado em ambiente de produção do projeto, o trecho de código que utiliza o ``.scheme`` deveria pegar o protocolo correto sem a necessidade de forçamos o uso de **https**.
> Adiciona um parametro de configuração para forçar o uso de https na formação das tags do google. 

- opac/webapp/static/less/article.less
Criação da classe thumbImg. A classe deve ser utilizada nas imagens dentro do artigo. Deve-se substituir thumb por thumbImg quando se necessita remover uma imagem de background e adicionar na própria tag img. 
No corpo do artigo, quando temos uma imagem em anexo, ela é exibida da seguinte maneira:
```
<div class="thumb" style="background-image: url(https://minio.scielo.br/documentstore/1678-2690/HvLdh4DtPD6YqV8WY3hNHPy/253016f9008b394cf453f197ff568fe31415fe6c.jpg);">
Thumbnail
<div class="zoom"><span class="sci-ico-zoom"></span></div>
</div>
```
Porém desta forma, não é possível ler / visualizar a imagem no que se diz respeito a preservação digital.
A solução para isso é remover a imagem do atributo css background-image e adicionar em uma tag img simples, padrão do html.
A solução consite …
> Imagem artigo - Preservação digital

- Dockerfile
- Dockerfile-dev
- docker-compose-dev.yml
- requirements.txt
* Alterar o comando do servidor de desenvolvimento para utilizar pseudo-threads.
* Atualiza a versão do Python 3.5 para Python 3.6, adiciona **gevent** como dependência e atualiza a versão do **Gunicorn**.
Rodando a aplicação em ambiente de desenvolvimento com ``docker-compose -f docker-compose-dev.yml build`` e ``docker-compose -f docker-compose-dev.yml up -d``
Acessando a aplicação e verificando se tem uma melhoria na velocidade de repostas das páginas.
N/A
N/A
N/A
N/A
> Altera a forma do uso de threads no Gunicorn. 

- opac/webapp/main/views.py
- opac/webapp/templates/errors/500.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- opac/webapp/translations/pt_BR.UTF-8/LC_MESSAGES/messages.po
Adiciona uma verificação nas rotas legadas dos PDFs para garantir que não levante uma exceção ao tentar acessar um PDF em que não exista o periódico na coleção.
Esse PR também remove o texto "Nossos engenheiros foram notificados." dos erros com status code 500.
No módulo: opac/webapp/main/views.py
Para teste manual é necessário algumas URL para PDFs com rotas legadas, segue: 
Rotas em que o periódico não exita: 
- /pdf/ijmorphol/v39n1/0717-9502-ijmorphol-39-01-70.pdf
- /pdf/rmie/v26n90/1405-6666-rmie-26-90-887.pdf
- /pdf/ride/v11n22/2007-7467-ride-11-22-e047.pdf 
- /pdf/orl/v81n3/0718-4816-orl-81-03-0397.pdf
- /pdf/eia/v17n34/2463-0950-eia-17-34-113.pdf
Rota onde o periódico exista e o PDF não:
- /pdf/aabc/v17n34/2463-0950-eia-17-34-113.pdf
Para a URL onde o periódico não exista deve …
> Adiciona uma verificação nas rotas legadas dos PDFs para garantir um 404 quando o periódico não existe.

- opac/webapp/main/views.py
- opac/webapp/templates/issue/toc.html
Garante que o parâmetro section_filter funcione somente quando a variável de confirguração **FILTER_SECTION_ENABLE** esteva como True e adiciona o atributo **rel="nofollow"** nos links do section_filter.
Analisando o módulo: opac/webapp/main/views.py e opac/webapp/templates/issue/toc.html
Acessando a página do Table of Contents com um parâmetro no QueryString ?section=bla
Exemplo: http://localhot:8000/j/aabc/i/2021.v93n1/?section=bla
Repare que esse parâmetro fica desativado caso a variável de ambiente **OPAC_FILTER_SECTION_ENABLE** esteja como False.
N/A
Tíquete relacionado: https://github.com/scieloorg/opac/issues/2139
N/A
> Garante que o parâmetro section_filter funcione somente quando a variável de confirguração FILTER_SECTION_ENABLE

- opac/webapp/templates/article/includes/modal/download.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- opac/webapp/translations/pt_BR.UTF-8/LC_MESSAGES/messages.po
Adiciona uma verificação de ausência do campo PDF e apresenta uma msg informando para o usuário que o PDF está indisponível por conta de o SciELO não ter recebido o ativo.
No template: opac/webapp/templates/article/includes/modal/download.html
Acessando um artigo sem **PDF**.
Esse é um exemplo: https://www.scielo.br/j/pusp/a/s63y4NmBfsHYpwm3gtw4wFD/?lang=pt#
Irei disponibilizar um exemplo em homologação para validação 
Esse PR mostra uma msg para o usuário, mas é importante saber que existe a possibilidade dele também esconde casos onde recebemos o PDF e não está disponível no site.
Tíquete referente: #2093 
N/A
> Adiciona uma verificação de ausência do campo PDF. 

- opac/tests/test_controller.py
- opac/tests/utils.py
- opac/webapp/controllers.py
Inibe a disponibilização de artigos que estão em "embargo", usando como filtro o campo `publication_date`.
por commits
Edite o campo `publication_date` de um artigo, colocando uma data futura. Este artigo não deve ficar acessível, nem apresentar em nenhuma listagem como sumário, nem ser contabilizado. Ou seja, deve ter o mesmo comportamento de um artigo não publicado.
n/a
n/a
n/a
n/a
> Inibe a disponibilização de artigos que estão em "embargo"

- opac/webapp/admin/views.py
- opac/webapp/config/templates/testing.template
- requirements.txt
Atualiza o Flask Admin para a versão 1.5.8
Por commit. 
Sugiro realizar os teste automáticos e rodar a aplicação utilizando a área administrativa. 
```
make test
```
Para não obtermos o erro:
```
TypeError: sequence item 0: expected str instance, _LazyString found
```
Tivemos que realizar alteração no ModelView do admin, assim como explicado no link: https://github.com/flask-admin/flask-admin/issues/1790
N/A.
Essa atividade está com riso de segurança, veja: https://github.com/scieloorg/opac/security/dependabot
N/A.
> Atualiza o Flask Admin para a versão 1.5.8

- opac/webapp/admin/views.py
- opac/webapp/templates/admin/pages/add.html
- opac/webapp/templates/admin/pages/edit.html
Adiciona a funcionalidade de persistir os dados das páginas de 30 em 30 segundos.
Sugiro revisar pelos modulos: 
- opac/webapp/admin/views.py 
- opac/webapp/templates/admin/pages/add.html
- opac/webapp/templates/admin/pages/edit.html
Subindo uma instância do opac localmente e acessando o ambiente de administração e realizando alguma alteração nas páginas secundárias. 
Essa funcionalidade tenta garantir que seja salvo os dados das páginas secundárias em tempo de edição. Está configurado para ser salvo de 30 em 30 minutos os dados da página secundária, **caso haja alguma mudança nos dado**s. 
Segue algumas imagens da nova funcionalidade: 
Não temos um tíquete para essa atividade mas temos ela como demanda na nossa planilha de atividade. 
Esse tíquete tem como objetivo também diminuir a …
> Adiciona a funcionalidade de persistir os dados das páginas de 30 em 30 segundos.

- opac/tests/test_admin_views.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/templates/admin/pages/edit.html
- requirements.txt
Adiciona a funcionalidade de deixar as páginas secundárias como rascunho. Atualizado a versão do opac_schema para v2.63
Por commit.
Acessando a área administrativa das páginas secundárias e observando que existe uma opção de marcar como rascunho.
**Importante:** As páginas em rascunho não são apresentadas no site.
#2113 
N/A
> Adiciona a funcionalidade de deixar as páginas secundárias como rascunho.

- opac/webapp/templates/admin/pages/edit.html
Corrigi erro enviado no PR: https://github.com/scieloorg/opac/pull/2183
Sugiro revisar pelos modulos:
opac/webapp/templates/admin/pages/edit.html
Subindo uma instância do opac localmente e acessando o ambiente de administração e realizando alguma alteração nas páginas secundárias.
Essa funcionalidade tenta garantir que seja salvo os dados das páginas secundárias em tempo de edição. Está configurado para ser salvo de 10 em 10 minutos os dados da página secundária, porém não estava persistindo os dados do conteúdo, já que a forma de obter os dados é com **CKEDITOR**. 
N/A
https://github.com/scieloorg/opac/issues/2114
N/A
> Ajusta a obtenção dos parâmetros para compor o POST do ajax de atualização dos dados do formulário.

- opac/tests/test_legacy_urls.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- requirements.txt
Atualiza a versão do opac_schema para v2.65, adiciona teste para obter pdfs da (URL) legada para suplemento e adiciona uma nova função no **controller** para entrar a URL legadas para suplemento.
Por commit.
É possível acessando uma rota como essa: http://<HOST>/pdf/aabc/v92.n2/0001-3765-aabc-92-suppl01-e20181357.pdf
**IMPORTANTE**: É necessário que existe uma **mat_suppl** em algum registro do tipo Article no na base de dados do site.
Essa implementação reutilizou a rota já existente para os /pdf(s) dos artigos, reparem esse reuso na views.py alterado.
Para rotar somente os do legacy_route: `export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test -p "test_legacy_urls"`
N/A
#2220 
https://github.com/scieloorg/opac-airflow/issues/315
N/A
> Adiciona a capacidade de resolver URL legadas para material suplementar.

- opac/webapp/config/default.py
- requirements.txt
Atualiza a versão do packtools para 2.9.3 e o valor padrão da variável `DEFAULT_MATHJAX_CDN_URL` que indica o renderizador de fórmulas
por commits
Ver https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-63512018000200385&lng=en&nrm=iso&tlng=pt
n/a
#1160 
n/a
> Corrige apresentação de alguns casos fórmulas em LaTeX que não estavam renderizando corretamente

- opac/tests/test_legacy_urls.py
- opac/webapp/main/views.py
Garante que o idioma seja considerado no redirect para os PDFs
Sugiro por commit 
Sugiro rodar os testes ou acessa uma rota para um PDF com endereço antigo, exemplo: 
http://www.scielo.br/scielo.php?script=sci_pdf&pid=S0104-11692021000100300&tlng=en
Comando para executar os testes:
```
export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test -p "test_legacy_urls"
```
N/A
Screenshots da execução dos testes: 
N/A
N/A
> Garante que o idioma seja considerado no redirect para os PDFs

- requirements.txt
Atualiza a versão do packtools 2.9.7 que resolve apresentação de cartas, afiliações e orcid
por commits
veja https://github.com/scieloorg/packtools/pull/305
n/a
n/a
Fix #2308
Fix #2306
Fix #2146
Fix #2277
n/a
> Atualiza a versão do packtools 2.9.7 que resolve apresentação de cartas, afiliações e orcid

- opac/webapp/static/less/journal.less
Corrige as dimensões do logo do periódico na tela do artigo.
acesse a tela do artigo e verifique as dimensões do logo do periódico.
Ela deve estar setada como width: 100% apenas no mobile.
Nos demais dispositivos a largura é automática e a altura máxima é de 200px.
Siga o passo anterior.
sem contexto específico.
Não foi criado um ticket. Apenas relatado o bug.
--
> correção de dimensões do logo do periodico

- opac/webapp/templates/article/base.html
Comenta um trecho de código para que o icone do dimensions volte a funciona, esse trecho foi adicionado para garantir que o mathjax funcione no celular, mas detalhes sobre essa implementação e seus motivos pode ser encontrado nesse link: https://github.com/scieloorg/opac/issues/2376
Pelo template: opac/webapp/templates/article/base.html
Acessando a página de uma artigo e clicando nas métricas. 
N/A
N/A
N/A
>  Comenta um trecho de código para que o icone do dimensions volte a funcionar.

- opac/webapp/static/less/journal.less
Corrige o tamanho do logo do periódico na tela do periódico sem interferir no tamanho do logo do periódico na tela do artigo
acesse a home do periódico e verifiquei se o logo do cliente fica sobre outros elementos da interface. Não deve ficar. O logo do periódico na tela do periódico está setado para ocupar 100% da largura do espaço onde ele está inserido. Dessa maneira não deve sobrepor nenhum outro item.
Siga o passo anterior
Atualize o sistema, rode o gulp para gerar os css. Acesse a pagina do periódico. Veja o comportamento do logo. Execute esse teste com vários periódicos diferentes para ver se com a variação de tamanho de logo o problema persiste. Não deve persistir.
Acesse a tela do artigo e verifique o tamanho do logo.
-
-
-
> Correção tamanho do logo do periodico na tela do periodico 

- opac/webapp/templates/article/includes/alternative_header.html
- opac/webapp/templates/collection/includes/header.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/header.html
Ajusta o novo logo scielo-25 anos nos headers das telas em que ele aparece. As telas corrigidas foram: home, periódico e artigo mobile e desktop. As telas que exibem o alternative header após a rolagem do scroll foram ajustadas também.
rode o sistema e navegue. No header, parte superior do sistema onde aparece o logo do SciELO deve exibir somente o logo scielo 25 anos.
1 - cadastrar o logo scielo 25 anos no admin do sistema. É importante que a url do logo seja no mesmo servidor em que o sistema esteja rodando. Caso contrário, o chrome ou outro navegador pode bloquear o carregamento da imagem externa.
2 - navegar por todas as telas do sistema em modo desktop. Deve ser possível visualizar somente o logo scielo 25 anos no header do sistema. Navegar também na resolução mobile quando estiver …
> ajuste logo scielo 25 anos no header 

- opac/webapp/main/views.py
Alterar a forma de identificar quando é uma requisição via ajax.
Por commit 
Utilizando as partes do site que tenha uso de ajax e realizando envio de formulário de erro.
Essa alteração é necessário por conta da versão do werkzeug que não dá mais suporte para **is_json**
N/A
N/A
N/A
> Alterar a forma de identificar quando é uma requisição via ajax.

- opac/webapp/static/less/scielo-portal.less
- opac/webapp/templates/base.html
Atualiza a classe .floatingBtnError do arquivo scielo-portal.less 
e também adiciona um texto ao botão no arquivo base.html
1 - gere os arquivos css a partir dos arquivos .less
2 - limpe o cache
3 - rode o sistema e verifique que o botão deve ser visualizado fixado no lado direito da tela.
Siga os passos anteriores.
O botão em questão está com um atributo translate rotate -90. Isso quer dizer que ele está sendo girado no sentido anti-horário, para que o texto fique de baixo para cima. Junto com esse atributo rotate, foi adicionado um atributo right:-80px. Portanto, caso o texto do botão seja alterado, possivelmente será necessário alterar o atributo right também. Este atributo right está diretamente relacionado ao tamanho do texto inserido dentro do botão.
Caso seja necessário alterar …
> Botão Reportar Erro / Acessibilidade

- opac/webapp/static/less/scielo-portal.less
Atualiza a classe .floatingBtnError do arquivo scielo-portal.less,
Corrige o posicionamento do botão independentemente da quantidade de caracteres do botão.
1 - gere os arquivos css a partir dos arquivos .less
2 - limpe o cache
3 - rode o sistema e verifique que o botão deve ser visualizado fixado no lado direito da tela.
Siga os passos anteriores.
Está funcionando para os labels no idioma en, es e pt
Sem ticket - urgente.
-
> Correção do css do botão floatingBtnError

- opac/webapp/templates/article/base.html
- opac/webapp/templates/article/detail.html
- opac/webapp/templates/article/includes/related-article.html
- requirements.txt
Adiciona a caixa amarela contendo lista de documentos relacionados quando não foi gerada pelo packtools
por commits
Acessando a página do artigo que tem errata, ou que tem comentários, que tem comentários, pois geralmente não foi inserida a tag related-article neste tipo de documento.
https://www.scielo.br/j/rbso/a/Km3dDZSWmGgpgYbjgc57RCn/?lang=pt
Sua errata
https://www.scielo.br/j/rbso/a/rj76QtnmbLz5w5YpfV7gTTL/?lang=pt
Foi sugerido que passassem a inserir a tag. Este código deve funcionar para ambas as situações.
Está sem a caixa
Sua errata tem a caixa gerada pelo packtools
#2389 
#2424
#2352
n/a
> Adiciona a caixa amarela contendo lista de documentos relacionados quando não foi gerada pelo packtools

- opac/webapp/templates/article/base.html
- requirements.txt
Corrige apresentação da caixa amarela que deve ser apresentada via javascript se não foi gerada pelo packtools.
por commits
https://www.scielo.br/j/trans/a/SjTdb8jgPc7Lg6d4X8NNDTN/?lang=es (está sem a caixa, mas tem que ter)
https://www.scielo.br/j/trans/a/5fw5pdvcC8vZLQGYnMB4sjn/?format=html&lang=pt
n/a
Veja o html source que há 1 related-article panel
https://github.com/scieloorg/opac/issues/2352
n/a
> Corrige apresentação da caixa amarela

- requirements.txt
- Acrescenta na seção de Histórico, o link de preprint, que não tem data preprint associada
- Apresenta a lista de materiais suplementares que foram indicados em `article-meta` de acordo com o issue #2506
por commits
Consultar os issues #2506, #2423, #2424
n/a
Ver os PR
https://github.com/scieloorg/packtools/pull/358
https://github.com/scieloorg/packtools/pull/359
#2506, #2423, #2424
n/a
> Atualiza a versão de packtools 2.17.8

- opac/webapp/templates/base.html
Visando facilitar a encontrabilidade do botão Acessibilidade / Reportar erro por leitores de tela, o botão foi colocado mais próximo possível da abertura da tag body. Dessa maneira, ao se acessar o sistema e teclar tab o botão passa a ser um dos primeiro itens a serem selecionados.
Este foi um ajuste simples de posicionamento de HTML. Portanto não haverá mudanças visuais na tela.
Uma forma simples de testar é ao acessar a aplicação, pressionar a tecla tab do teclado e verificar que o botão Acessibilidade / Reportar Erro passa a ser um dos primeiros itens a serem selecionados.
Siga os passos descritos anteriormente.
É importante limpar o cache antes de efetuar os testes.
#2534 
--
> Correção acessibilidade. Troca da posição do botão acessibilidade

- opac/webapp/main/views.py
Remove rota desnecessária para a contrução da URL para os diversos formatos de apresentação do artigo e para acesso ao text e pdf.
Por commit 
Acessando o link para o PDF na página do artigo.
Isso corrige um bug introduzido no release https://github.com/scieloorg/opac/releases/tag/v4.1.2
N/A
https://github.com/scieloorg/opac/issues/2578
N/A
> Remove rota desnecessária para a contrução da URL para os diversos formatos de apresentação do artigo e para acesso ao text e pdf.

- opac/webapp/controllers.py
Garante que a contagem de quantidade de '**volume_issue**'(publicação continua) seja a mesma do **issue toc**.
Por commit 
Para teste manual acesso a página **/j/cta/grid** do site e veja a quantidade de artigos para o Volume 42 do ano 2022. 
Compare com a quantidade de itens no **/j/cta/i/2022.v42/** veja que a quantidade é a mesma.
Esse bug acontece por que não estava na contagem dos artigo considerando que deve se contabilizado somente artigos públicos.
https://github.com/scieloorg/opac/issues/2455
N/A
> Garante que a contagem de quantidade de 'volume_issue'(publicação continua) seja a mesma do issue toc.

- opac/webapp/templates/article/base.html
- requirements.txt
Adiciona melhorias na busca pelo ID do **SCIMAGO** para montar o link, para a instituição na página do artigo.
Por commit. 
Rodando a aplicação, acessando o modal de autores e realizando verificações das afiliações(instituições) em: https://www.scimagoir.com/
Essa é uma melhoria, já que a implementação anterior tentava obter a afiliação a partir de um string sem qualquer semântica.
Foi possível após a versão **3.0.1** do **packtools**.
N/A
PR do packtools com a implementação das instituições: 
https://github.com/scieloorg/packtools/pull/367
N/A
> Melhorias na implementação do SCIMAGO na página do artigo.

- opac/webapp/templates/article/includes/related-article.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
Corrige texto da caixa amarela que aparece em artigo comentado.
O texto deve indicar que o artigo tem comentário, mas aparece por engano que tem adendo
por commits
Ver https://github.com/scieloorg/opac/issues/2603
n/a
n/a
https://github.com/scieloorg/opac/issues/2603
n/a
> Corrige texto da caixa amarela que aparece em artigo comentado

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
Esse PR melhora a implementação do SCImagoIR na página do artigo. 
Garante que já esteja o ícone no modal antes mesmo do link ser montado.
Por commit 
Para testar manualmente é necessário ter uma instância do SciELO rodando localmente e com acesso a artigo é possível verificar as imagens do SCImagoIR no modal.
Essa é uma melhoria de uma implementação anterior.
Essa implementação não afeta o tempo de carga da página do artigo.
Algumas imagens dessa implementação funcionando: 
Essa demanda não tem um tíquete.
N/A
> Melhora a implementação do SCImagoIR na página do artigo

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
Esse PR liga e desliga a carga dos links do SCImago na página do artigo
Por commit.
Para testar manualmente é necessário ter uma instância do SciELO rodando localmente e com acesso a artigo é possível ligar e desligar a carga dos links no modal ou na carga da página.
**IMPORTANTE**: Essa alteração é perigosa, pois, ao ligarmos a carga dos links do SCImago na página do artigo duplicamos o tempo de finalização da carga da própria página. 
Os params que ligam essa funcionalidade estão todos alinhados a deixar a carregamento desses links no modal, o param **SCIMAGO_IR_LOAD_ON_MODAL** tem valor padrão **True**
Aumento no tempo de carga da página: 
De 1.8s
para 3.8s
Possíveis problemas que podem ser recorrentes ao ligarmos a carga dos links do SCImago na página do artigo: 
Essa demanda não tem …
> Scimago ON OFF modal load

- opac/webapp/controllers.py
Adiciona na consulta a artigos, o PID de artigo "corrigido", a fim de retornar artigos que foram criados usando um ISSN anteriormente registrado. Também elimina consulta excedentes, adotando o uso de `Q()`.
por commits
Ver #2673
n/a
n/a
#2673
n/a
> Adiciona na consulta a artigos, o PID de artigo "corrigido"

- opac/webapp/templates/article/base.html
- requirements.txt
Garante que não quebre a posição do link do **SCIMAGO** instituição para a lista de autores
Sugiro avaliar o código em javascript do arquivo: ``opac/webapp/templates/article/base.html``
Subindo uma instância local do opac e acessando a página do artigo, clicando no link, veja: 
Anteriormente o link estava sendo apresentado após o **ORCID**, veja: 
Agora esta correto na linha onde temos uma instituição, veja: 
Não tem tíquete para essa atividade.
N/A
> Garante que não quebre a posição do link do scimago instituição para a lista de autores

- opac/webapp/static/less/article.less
Corrige o problema de margem negativa relatado no ticket 2731.
Remove a definição de margem negativa deixando assim o layout correto.
Carregue os arquivos desse commit, gere via gulp os arquivos css estaticos e abra um dos artigos citados no issue 2731 ou similar. Veja que o erro foi corrigido. 
Siga os passos anteriores. Muito importante gerar os arquivos estáticos e limpar o cache antes de testar.
O arquivo modificado foi um .less, portanto é necessário gerar os css estáticos. Depois disso limpe o cache e teste na tela do artigo.
#2731 
--
> Remoção da definição de margem refList Artigo - issue 2731

- opac/tests/test_main_views.py
- opac/webapp/controllers.py
Garante a apresentação do botão de ``ahead`` somente quanto há artigos.
Sugiro que olhando o código.
Para testas é possível rodando os teste unitários: 
```shell 
make test
```
Esse PR garante que o botão deve aparecer somente se existe artigos na grade do periódico.
Alguns testes manuais: 
#2022 
N/A
> Garante a apresentação do botão de ``ahead`` somente quanto há artigos.

- opac/webapp/main/views.py
Corrige a atribuição de valor para o parâmetro begin_date
Por commits
Executando o acesso a:
https://www.scielo.br/api/v1/counter_dict?end_date=2023-08-08&begin_date=2017-01-01&limit=100&page=4
que deve retornar dados mais antigos e não 30 dias antes de 2023-08-08
Este endpoint foi criado para uso no procedimento de contagem de acessos.
E está sendo reaproveitado no core para carga dos XML de scielo.br no pid provider, para garantir a atribuição / checagem de pid v3 consistente.
n/a
n/a
n/a
> Corrige a atribuição de valor para o parâmetro begin_date

- requirements.txt
Atualiza a versão de packtools que corrige apresentação de xref[@ref-type='bibr'] para o padrão autor, ano
n/a
n/a
n/a
n/a
https://github.com/scieloorg/packtools/pull/519
n/a
> Atualiza a versão de packtools que corrige apresentação de xref[@ref-type='bibr'] para o padrão autor, ano

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/includes/levelMenu.html
Corrige a identificação de "último número".
Um "número" (fascículo) é um fascículo da publicação regular ou contínua, não pode ser considerado nem especial, nem suplemento, nem ahead of print. No entanto, para a navegação entre todos os componentes do periódico (números regulares, contínuos, especiais, suplementos, ahead of print), todos são considerados. 
Por commits
Navegando entre as páginas do periódico: home, about, fascículos etc, nas páginas.
Ler #99
PR baseado em https://github.com/scieloorg/opac_5/pull/108, com melhorias
n/a
#99 
n/a
> Corrige a identificação do "último número"

- requirements.txt
Atualiza a versão do packtools para trocar http para https para orcid, lattes, researcherid
por commits
Acessando a página do artigo, abrindo o modal de autores e verificando a apresentação dos ORCID que devem estar com `https://`
n/a
n/a
https://github.com/scieloorg/packtools/pull/583
n/a
> Atualiza a versão do packtools para trocar http para https para orcid, lattes, researcherid

- requirements.txt
Atualiza dependência opac_schema para versão v2.8.0
pelos commits
1. docker-compose -f docker-compose-dev.yml build --no-cache
2. make up 
n/a
n/a
n/A
n/a
> Atualiza dependência opac_schema para versão v2.8.0

- opac/webapp/config/default.py
- opac/webapp/templates/includes/footer.html
- requirements.txt
Adiciona a licença no rodapé do site e atualiza o opac_schema.
Pelos commits
Sugiro que seja executado a aplicação e verificado a licença no rodapé
Com essa alteração é possível ligar/desligar a licença no rodapé 
Repare que temos novas variáveis de ambiente: 
* SITE_LICENSE_ENABLE
* SITE_LICENSE_NAME
* SITE_LICENSE_URL
* SITE_LICENSE_IMG_URL
Algumas telas com a licença: 
https://github.com/scieloorg/opac/issues/3127
> Adiciona a licença no rodapé do site e atualiza o opac_schema
