- app/admin/views.py
- app/controllers.py
- app/main/views.py
- app/templates/article/includes/levelMenu.html
- app/utils.py
Essa atividade impacta no: Periódico, Fascículo e no Artigo, realizei uma bateria de testes para verificar a funcionalidade, segue abaixo: 
Nesse testes demonstro as consequências as alteração de visibilidade para o três item citados: 
Cenários para serem avaliadas após as mudanças de visibilidade no admin
Utilizando a CSP (Cadernos de Saúde Pública) como exemplo:
Cenário 1:
Tornando uma revista não pública:
Não deve aparecer os seguintes links para a própria revista e seus 'filhos'
http://localhost:5000/journals
Teste realizado - OK - (A revista não aparecer na listagem)
http://localhost:5000/journals/e6199be0ccac4af4ae7b2b775d6fc35c (página da revista)
Teste realizado - OK - Retorna página de 404 - line 48 e 49 da main.view.py
Atenção:
Precisa recadastrar o úlitmo fascículo para o caso …
> Funcionalidade de Publicar e "Despublicar" no Admin do Opac

- app/__init__.py
- app/controllers.py
- app/errors.py
- app/models.py
- app/notifications.py
- app/templates/403.html
- app/templates/404.html
- app/templates/500.html
- app/templates/admin/auth/login.html
- app/templates/admin/auth/reset.html
- app/templates/admin/auth/reset_with_token.html
- app/templates/admin/auth/unconfirm_email.html
- app/templates/admin/index.html
- app/templates/admin/opac_base.html
- app/templates/email/activate.html
- app/templates/email/recover.html
- app/utils.py
- config/default.py
- config/development.py
- config/production.py
- instance/config.py.template
- manager.py
Os textos dos templates definidos pelo mockup não foram modificados.
FIXES: #11
> #11 - Revisar mensagens para o usuário, comentários, docstring, etc

- manager.py
- migrations/README
- migrations/alembic.ini
- migrations/env.py
- migrations/script.py.mako
- requirements.txt
Adicionar a funcionalidade para poder migrar o banco de dados relacional, sem ter perda de dados.
ver: https://flask-migrate.readthedocs.org/en/latest/#command-reference
- FIXES: #15
> dependências, comandos e pasta de migração inicial

- app/__init__.py
- app/admin/views.py
- app/main/__init__.py
- app/main/views.py
- config/logger.ini
> Definição de infra para loggging

- .travis.yml
> Update pack tool branch repo

- .gitignore
- app/translations/messages.pot
Acrescento o arquivo .pot necessário para a integração com Transifex
> Versionado do arquivo ".pot" para integração com Transifex

- app/templates/403.html
- app/templates/404.html
- app/templates/500.html
- app/templates/article/abstract.html
- app/templates/article/detail.html
- app/templates/article/includes/alternative_header.html
- app/templates/article/includes/levelMenu.html
- app/templates/collection/includes/email_modal.html
- app/templates/collection/includes/header.html
- app/templates/collection/includes/levelMenu.html
- app/templates/collection/index.html
- app/templates/collection/list_alpha.html
- app/templates/collection/list_institution.html
- app/templates/collection/list_theme.html
- app/templates/includes/footer.html
- app/templates/includes/format_journal_row.html
- app/templates/issue/grid.html
- app/templates/issue/toc.html
- app/templates/journal/detail.html
- app/templates/journal/includes/alternative_header.html
- app/templates/journal/includes/contact_footer.html
- app/templates/journal/includes/header.html
- app/templates/journal/includes/levelMenu.html
- app/translations/en/LC_MESSAGES/messages.po
- app/translations/es/LC_MESSAGES/messages.po
- app/translations/messages.pot
> Update public site templates with translate tags

- app/__init__.py
- app/templates/base.html
- config/default.py
> Adicionado G.A code no OPAC

- Makefile
- requirements.txt
- atualização no requirements para a versão mais recente do Admin
- nova regra no make file para executar um ``pip install --upgrade -r requirements.txt``
> #50 - Atualizar a versão do Flask-Admin

- app/admin/views.py
- app/choices.py
- app/controllers.py
- app/main/views.py
Fix.: R15, R16, R21, R20.
Importante: Atualizar o opac_schema para a versão v1.1
> Adicionado a funcionalidade de "despublicar" marcando um motivo R15, R16, R21, R20

- app/admin/custom_filters.py
- app/admin/views.py
> Search in Article allow journal, issue

- app/admin/custom_filters.py
- app/admin/views.py
> Add Article filters by journal, issue, is_aop

- app/admin/views.py
> Search in Issue allow title_iso, short_title

- app/controllers.py
- app/main/views.py
> Refatoração do controller.py para que tenhamos mais contexto na views

- app/admin/views.py
> Corrección de etiqueta "É AOP?"

- app/templates/collection/includes/email_modal.html
- app/translations/en/LC_MESSAGES/messages.po
- app/translations/es/LC_MESSAGES/messages.po
- app/translations/messages.pot
> corrección de texto en ingles en el template

- app/translations/es_ES/LC_MESSAGES/messages.po
- app/translations/es_MX/LC_MESSAGES/messages.po
- config/default.py
> Agregados catálogos "es_ES" y "es_MX" para traducciones

- app/controllers.py
- manager.py
- tests/test_controller.py
- tests/test_opac_models.py
- tests/utils.py
Resolve parcialmente o tk #75. Estamos com 74% de teste nesse módulo.
> Adiciono teste para o módulo controllers

- requirements.txt
> Ajuste no requirements.txt para instalar packtools 0.9.0

- app/controllers.py
- tests/test_controller.py
> Complemento dos testes do tk75

- app/admin/views.py
- app/controllers.py
- app/utils.py
- tests/test_controller.py
> Finalização dos testes para o controllers

- app/admin/views.py
- app/controllers.py
- tests/base.py
- tests/test_admin_views.py
- tests/test_controller.py
- tests/utils.py
novos tests com covertura de 72%
- test_access_to_admin_index_must_redirect_to_login_form
- test_admin_index_content_counts_is_ok
- test_confirm_email_with_invalid_token_raise_404_message
- test_confirmation_email_send_email_with_token
- test_create_user_from_admin_page_creates_a_new_user
- test_email_confimation_token_of_invalid_user_raise_404_error_message
- test_invalid_credentials_login_must_show_validation_error
- test_invalid_password_login_must_show_validation_error
- test_invalid_user_login_must_show_validation_error
- test_link_sent_via_email_to_reset_password_works_fine
- test_login_page_must_have_link_to_password_reset
- test_login_page_must_have_set_language_links
- test_login_successfully
- test_login_valid_user_with_invalid_password_raise_error_msg
- …
> #72 - tests admin.views.py

- app/__init__.py
> add ProxyFix para deploy

- app/admin/custom_filters.py
- tests/test_admin_custom_filters.py
> Agregados tests para admin.custom_filters

- Dockerfile
- app/utils.py
- requirements.dev.txt
- requirements.production.txt
- tools/am2opac.py
Esse ajuste visa permitir que o processamento possa ser realizado após o UP do docker.
> Ajuste no script de importação, dockerfile e requirements.txt

- app/config/default.py
- app/config/templates/development.template
- app/config/templates/testing.template
- app/main/views.py
- app/templates/errors/500.html
- app/templates/errors/base.html
- tools/am2opac.py
> Ajuste nas msgs para os recursos

- .gitignore
- docker-compose.yml
- opac/manager.py
- opac/webapp/__init__.py
- opac/webapp/admin/custom_fields.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/models.py
- opac/webapp/utils.py
- requirements.txt
- instalar requirements: Pillow e SQLAlchemyUtils
- ajustes no docker-compose.yml
- novo comando no manager para criar as tabelas
- novas variáveis de ambiente na configuração: OPAC_MEDIA_ROOT e OPAC_MEDIA_URL
> Modelos: Image e Files, e ModelAdminViews para upload de estáticos

- opac/tools/am2opac.py
- opac/webapp/admin/views.py
> Ajuste no importador e excluido campos com relação com a entidade resource

- opac/tests/test_admin_views.py
- opac/webapp/admin/views.py
- opac/webapp/utils.py
> Removido a opção de re-construir o HTML do artigo no Admin.

- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/includes/footer.html
- requirements.txt
- setup.py
- instalar versão 1.9 do opac_schema :warning: 
- ajustes no setup.py :point_left: 
- codigo que adiciona objetos no objeto global ``g``
- tests! :+1:
> #123 - Adicionar o conteúdo dinâmico na lista de logos dos financiadores

- opac/tests/test_interface_header.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/includes/header.html
> Adicionado a funcionalidade de trocar o idioma no site.

- opac/tests/test_interface_header.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/about.html
- opac/webapp/templates/collection/includes/levelMenu.html
- opac/webapp/templates/collection/metrics.html
- opac/webapp/templates/collection/search.html
- opac/webapp/templates/macros/menu.html
FIX: #126 
- novas views (placeholders) das páginas de busca, metricas e sobre scielo.
- testes de interface
- nova pasta templates/macros/ para organizar as macros.
> #126 - Colocar o menu na home para funcionar conforme o mockup

- opac/tests/test_main_views.py
- opac/webapp/templates/includes/footer.html
> #174 - Ajustar o endereço da coleção no rodapé do site

- opac/tests/test_admin_views.py
- opac/tests/test_interface_footer.py
- opac/tests/utils.py
- opac/tools/am2opac.py
- opac/webapp/admin/views.py
- opac/webapp/choices.py
- opac/webapp/templates/includes/footer.html
- requirements.txt
- setup.py
> Alterado a licença de uso da coleção compativel com a versão 2.1 do opac_schema.

- opac/tests/test_interface_header.py
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/includes/header.html
- opac/webapp/templates/collection/includes/nav.html
- opac/webapp/templates/journal/includes/header.html
> #149 - Conteúdo dinâmico no menu Superior.

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/static/js/journal_lists.js
- opac/webapp/templates/collection/list_alpha.html
- opac/webapp/templates/collection/list_institution.html
- opac/webapp/templates/collection/list_theme.html
- opac/webapp/templates/includes/footer.html
- requirements.txt
- setup.py
> #179 - Links para download em Excel e CSV nas listagens de períodicos

- opac/webapp/templates/journal/detail.html
> Ordenação das seções na página do periódico

- opac/tests/test_main_views.py
- opac/tools/am2opac.py
- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/admin/news/list.html
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/news/includes/collection_news_row.html
- opac/webapp/templates/news/includes/journal_news_row.html
- opac/webapp/utils.py
- requirements.txt
- setup.py
FIX #199 - erro ao deleter em lotes
FIX #124 - Noticias no home da coleção
FIX #145 - Noticia na página dos periódicos
> Noticias (CRUD no admin) e listagem no site collection index e journal detail

- opac/webapp/templates/base.html
- opac/webapp/templates/journal/includes/alternative_header.html
Fanfarronagem em ambiente de homologação.
> Adicionando bugherd

- opac/tools/am2opac.py
- opac/webapp/templates/collection/search.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/includes/header.html
- requirements.txt
> Adicionado o autor no Issue TOC e alterado a versão do Opac Schema

- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/__init__.py
- opac/webapp/config/templates/development.template
- opac/webapp/main/views.py
- opac/webapp/templates/article/abstract.html
- opac/webapp/templates/article/detail.html
- opac/webapp/templates/article/includes/alternative_header.html
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/macros/articles.html
> #256 - Mostrar somente PDF do artigo na página do artigo

- opac/tests/test_admin_views.py
- opac/tests/test_notifications.py
- opac/webapp/admin/views.py
- opac/webapp/notifications.py
- opac/webapp/utils.py
FIX #200
Os pasos para reproduzir o erro estão na descrição do ticket!
> #200 - Criar usuário sem conexão SMTP funcionando, levanta exceção mas cria usuário

- opac/webapp/templates/journal/includes/levelMenu.html
> Cambiar 'home' por 'home da revista' para páginas de la revista

- opac/webapp/templates/journal/includes/header.html
> Indicar el tipo de ISSN para las páginas de la revista

- opac/webapp/static/css/scielo-portal.css
- opac/webapp/templates/journal/includes/header.html
> Cambio de ubicación en la presentación de áreas temáticas

- opac/webapp/templates/includes/language.html
> #237 - Links de mudança de idiomas devem ser escritos no idioma original

- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/levelMenu.html
> #231 - Barra de navegação esta confusa no contexto do periódico

- opac/webapp/main/views.py
- opac/webapp/templates/issue/toc.html
> #247 - Reformulação de apresentação do Table of Contents

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/static/js/journal_lists.js
- opac/webapp/templates/collection/includes/list_journals_search_input.html
- opac/webapp/templates/collection/list_alpha.html
- opac/webapp/templates/collection/list_institution.html
- opac/webapp/templates/collection/list_theme.html
> #216 - Sugestão - Opção "Títulos-correntes" e "Títulos não-correntes"

- opac/webapp/__init__.py
- opac/webapp/controllers.py
- opac/webapp/static/css/style.css
- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
> Adicionado o título anterior na listagens

- opac/webapp/static/css/scielo-portal.css
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/macros/articles.html
- opac/webapp/translations/messages.pot
- requirements.txt
> Alterações no template do toc para mostrar corretamente o Resumo, Texto completo e PDF

- opac/tests/utils.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/issue/grid.html
- requirements.dev.txt
- requirements.production.txt
- requirements.txt
> #243 - Ahead of print não deveria ficar na grade de fascículos

- opac/tests/test_admin_views.py
- opac/webapp/admin/views.py
- opac/webapp/static/css/scielo-portal.css
- opac/webapp/static/css/style.css
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/detail.html
- requirements.txt
- setup.py
> Ajuste da legenda bibliografica para utilizar o formato legendarium

- opac/tests/test_interface_TOC.py
- opac/tests/test_interface_footer.py
- opac/tests/test_interface_journal_home.py
- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/__init__.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/alternative_header.html
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/collection/list_feed_content.html
- opac/webapp/templates/includes/format_journal_row.html
- opac/webapp/templates/issue/grid.html
- opac/webapp/templates/issue/toc.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/contact_footer.html
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/templates/journal/includes/levelMenu.html
- requirements.txt
Deixamos a URL algo mais palatável.
Olha que coisa mais linda: http://localhost:5000/icse/2009.v13n29/255-256/pt/ :-)
> Deixando a URL elegante no Site.

- opac/tests/test_interface_menu.py
- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/static/css/style.css
- opac/webapp/templates/admin/pressrelease/edit.html
- opac/webapp/templates/collection/includes/press_release.html
- opac/webapp/templates/collection/includes/press_release_modal.html
- opac/webapp/templates/collection/index.html
- requirements.txt
- setup.py
> Adicionando a interface do press release.

- Dockerfile-dev
- README.rst
- docker-compose-dev.yml
rodar: ``docker-compose -f docker-compose-dev.yml up``
Também pode atualizar o código fonte, e o gunicorn vai reiniciar para pegas as mudanças no código, sem precisar reconstruir a imgem
> Ajustes e incorporação do mailhog para capturar envio de emails

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/static/css/style.css
- opac/webapp/static/js/main.js
- opac/webapp/templates/collection/includes/email_modal.html
- opac/webapp/utils.py
> Agregada funcionalidad para compartir página por email

- opac/webapp/controllers.py
- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/templates/issue/toc.html
- requirements.txt
Atividades realizadas(bugs):
1. Corrigir links do texto no idioma certo, no TOC fix: #315
2. "None" na issue TOC fix: #314
3. Link para último número na listagem de periódicos esta levando à pagina do periódico fix: #307
> Referente aos Tks: 315, 314, 307

- Dockerfile
- Dockerfile-dev
- docker-compose-dev.yml
- docker-compose.yml
- definido usuário: **nobody** para não executar código como **root**
- ajustes para simplificar o ``docker-compose.yml`` seguindo o exemplo do ``docker-compose-dev.yml``
> [WIP] Ajustes no Dockerfile & docker-compose.yml (SEM ROOT)

- opac/webapp/static/css/style.css
- opac/webapp/templates/collection/includes/list_journals_search_input.html
- opac/webapp/templates/collection/includes/tmpl_journal_list_grouper_table_container.html
- opac/webapp/templates/collection/list_journal.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
> Traduções e ajuste de layout nas listagens de periódicos.

- opac/tests/test_interface_header.py
- opac/tests/test_interface_menu.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/journal/detail.html
- requirements.txt
- setup.py
> Garantindo que os dados do analytics não seja utilizado on the fly

- opac/tests/test_interface_menu.py
- opac/webapp/main/views.py
> Corrigi bug de sessão do idioma no Safari.

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- requirements.txt
> Ajuste de encoding download xls

- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/templates/includes/format_journal_row.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/header.html
> Abrir envío de manuscritos en nueva pestaña

- opac/webapp/controllers.py
- opac/webapp/main/views.py
> Ajuste no parametro da listagem temática de study_areas para subject_categories

- opac/webapp/static/js/main.js
> Fixes tk359

- .travis.yml
> Integração slack travis

- opac/webapp/templates/collection/includes/tmpl_journal_list_row.html
- opac/webapp/templates/collection/list_feed_content.html
- opac/webapp/templates/collection/list_journal.html
- opac/webapp/templates/includes/format_journal_row.html
> Ajustes de tradução

- opac/tests/test_main_views.py
- opac/webapp/templates/issue/grid.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
> Correções de tradução e erro na grafia

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/static/css/style.css
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/news/includes/issue_last_row.html
- opac/webapp/translations/messages.pot
> Números mais recentes na home do site

- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
> Atualização de traduções

- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/main/custom_filters.py
- opac/webapp/templates/news/includes/collection_news_row.html
- opac/webapp/utils.py
> Corrigindo hora das noticias na home page do site.

- opac/tests/test_admin_views.py
- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/templates/admin/index.html
- novos dados na home do admin
- ajustes no menu (ordem)
- ajustes nas colunas das listas
> Ajustar interface admin

- requirements.txt
- setup.py
Atualizando a versão do opac_schema.
> Atualizando a versão do OPAC Schema.

- docker-compose-build.yml
- docker-compose-dev.yml
- docker-compose.yml
Ajuste de hora e no hostname do container no docker-compose-dev.yml.
> Ajuste no compose files

- opac/webapp/templates/collection/index.html
Agora vai em erro quando a aplicação não estive com acesso ao banco de dados ou em a estrutura do banco.
> Ajuste na página incial.

- .gitignore
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/helpers/rss_feeds_importer.py
- opac/webapp/static/css/style.css
- opac/webapp/templates/admin/pressrelease/list.html
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/includes/press_release_modal.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/news/includes/journal_news_row.html
- opac/webapp/templates/press_release/includes/collection_press_releases_row.html
- opac/webapp/templates/press_release/includes/journal_press_release_row.html
- opac/webapp/utils.py
- requirements.txt
> Importa Press-Releases do Blog

- opac/webapp/controllers.py
- opac/webapp/helpers/rss_feeds_importer.py
> reverte a ordem de exibição da listagem de press releases

- opac/webapp/templates/press_release/includes/collection_press_releases_row.html
> Melhora exibição do press releases na home da coleção

- opac/webapp/static/css/scielo-portal.css
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/journal/detail.html
- opac/webapp/templates/press_release/includes/collection_press_releases_row.html
- opac/webapp/templates/press_release/includes/journal_press_release_row.html
- opac/webapp/templates/press_release/includes/press_releases_row.html
> Melhora exibição de press releases

- Dockerfile
- Dockerfile-dev
- opac/webapp/main/views.py
- opac/webapp/templates/collection/includes/email_modal.html
> FIX 563 - Erro no envio email com o botão: Compartilhar

- opac/webapp/static/css/style.css
- opac/webapp/templates/includes/footer.html
- opac/webapp/templates/journal/includes/contact_footer.html
- opac/webapp/templates/journal/includes/header.html
Fixes: #639 
Fixes: #635
Fixes: #638
Fixes: #640
Fixes: #292
> Ajustes de interface referente aos tickets: 636 635 638 640 292

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/detail.html
> 639 - Nova feature: Artigos mais recentes

- opac/webapp/templates/article/base.html
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/base.html
Não aprovar esse PR ainda falta alguns "metas" como mencionado na tabela do tk: https://github.com/scieloorg/opac/issues/656
> Adicionando os metatags que existem no modelo - Parte 1

- docker-compose-dev.yml
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/detail_pdf.html
- opac/webapp/templates/article/includes/floating_menu.html
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/article/includes/modal/download.html
- opac/webapp/templates/issue/toc.html
**Obs:** Precisa adicionar novas variáveis de ambiente para apontar ao server de SSM (homologação)
> FIX: ajustes para links de PDF usando uma view (generica) como proxy

- opac/manager.py
- opac/webapp/templates/journal/includes/header.html
> Adicionando link para corpo editorial e ajuste no cadastro das páginas secundárias

- opac/webapp/templates/article/includes/modal/related_article.html
> Ajustes URL para google schoolar: Artigos Similares e Artigos Citados

- opac/webapp/templates/article/includes/levelMenu.html
> 652 - Link para PDF mais visível

- opac/tests/test_interface_menu.py
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/journal/includes/levelMenu.html
Evita que gere URL inválidas no menu.
> Correções no menu level para evitar URL inválidas

- opac/webapp/main/views.py
> Fix bug708

- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/journal/includes/levelMenu.html
Não aprovar esse PR ainda é necessário testar no dispositivo.
> WIP: Correção do menu para IPAD

- opac/webapp/templates/article/includes/levelMenu.html
> ajuste: Erro de interface no botões de PDF - issue: 775

- opac/webapp/templates/collection/includes/header.html
> Ajuste nova classe para posicionar o logo da coleção corretamente

- opac/webapp/templates/article/includes/levelMenu.html
> ajuste botão de PDF (parte 2)

- opac/webapp/templates/article/detail.html
- opac/webapp/templates/article/includes/levelMenu.html
> Ajustes botões de PDF e layout errado dos artigos

- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/meta.html
Adiciona mais metas no header do artigo. Ref.: #656
> Adiciona a URL do PDF no meta

- opac/webapp/config/default.py
- opac/webapp/templates/base.html
> tk 815 - add conf para ativar visitor insights do pingdom

- opac/tests/test_admin_views.py
- opac/tests/test_models.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/models.py
- opac/webapp/utils/utils.py
> No admin, mostrar html de pág informativa quando acessado no modo de leitura

- requirements.txt
> Data de criação e atualização das páginas informativas no admin

- opac/webapp/controllers.py
relacionado com ausencia de articles no issue toc: ticket #893
quando tinhamos issues com o mesmo url_segment mas de tipo diferente a lista de articles era vazia, pq tinhamos 2 issues para o mesmo segment
> FIX: issue toc vazia para algumas issues

- opac/webapp/templates/includes/page_updated_at_info.html
> FIX: data em formato iso das páginas informativas (nas site público)

- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/templates/admin/audit_log/fields_data_table.html
- requirements.txt
> ADD audit log entry no admin

- Makefile
- opac/webapp/templates/issue/toc.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Atualiza os arquivo de traduções.
> Atualizar os arquivos .pot e po(s).

- opac/webapp/main/views.py
- opac/webapp/templates/email/email_form.html
**Importante**: Não aconselho atualizar a produção com a imagem gerada desse **PR**
ESSE  É PARA TESTE NO AMBIENTE DE HOMOLOGAÇÃO
> Adicionando uma view para o form de e-mail

- opac/webapp/templates/base.html
@jfunez 
Verifique se é essa a idéia!
> Adiciona temporariamente tags para o varnish

- opac/webapp/main/views.py
- opac/webapp/templates/base.html
Essa correção garanti que estamos dando preferência para o cabeçalho da requisição "accept-language". 
**IMPORTANTE**: Adicionei um print da variável session quando a aplicação está em modo debug temporariamente para o facilitar para o consultor.
> Ajuste no idioma na página inicial 

- opac/webapp/templates/base.html
- opac/webapp/templates/email/email_form.html
> Ajuste no modal para envio de e-mail com varnish

- opac/webapp/main/views.py
Adiciona um novo caminho virtual para imagem para o PubMed
Fixes: #980.
> Adiciona o caminho virtual para a imagem necessária para o PubMed

- Makefile
- opac/fixtures/default_info.json
- opac/manager.py
- opac/tests/test_admin_views.py
- opac/tests/test_main_views.py
- opac/tests/utils.py
- opac/webapp/admin/views.py
- opac/webapp/templates/includes/footer.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- requirements.txt
- Atualização da versão do OPAC-Schema
- Alteração do SponsorAdminView p/ a definição do campo Order e controle
de dados de Sponsor duplicado
- Alteração do rodapé p/ seguir a ordem estipulada no cadastro de
Sponsor
- Atualização dos arquivos de tradução
- Atualização dos testes das views de Admin e Main
> Inclusão do campo Order no Sponsor p/ determinar ordem de prioridade

- opac/webapp/templates/issue/grid.html
Related to #989.
suplemento de número = n suppl. x
suplemento de volume = suppl. x
> Exibição do número do suplemento de número na grade de issues

- docker-compose.yml
> [tk985] Configuração no docker-compose.yml para páginas secundárias

- opac/tests/test_admin_views.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- requirements.txt
- setup.py
relacionado com #983
Fixes #1032
> [tk1032][admin] Possibilitar a edição de scimago_id

- opac/webapp/templates/article/includes/modal/download.html
Referente ao bug #1039 
Fix: https://github.com/scieloorg/opac/issues/1039
> Remove o link do readcube na página do artigo

- docker-compose-build.yml
- docker-compose-dev.yml
- opac/tests/test_legacy_urls.py
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
> add suporte a urls legadas com script=sci_pdf

- opac/webapp/static/robots.txt
Adicionado `robots.txt` do scielo.br no projeto, com tudo desabilitado.
> Adiciona robots.txt

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Endpoint para acessar arquivo robots.txt
> Adiciona rota para arquivo robots.txt

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
- opac/webapp/static/robots.txt
- opac/webapp/templates/base.html
- opac/webapp/templates/email/email_form.html
- opac/webapp/templates/issue/base.html
- opac/webapp/templates/issue/grid.html
- opac/webapp/templates/journal/base.html
- opac/webapp/templates/journal/includes/contact.html
- opac/webapp/templates/macros/issue.html
- opac/webapp/templates/news/includes/issue_last_row.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Na Home/Feed de números mais recentes, ajustar o formato
Remover Número: None
Incluir Suplemento: valor, quando aplicável
Fixes #904
Duplicado com #971
> [tk904] Remover "Número: None" da Home

- Dockerfile
- Dockerfile-dev
- docker-compose-build.yml
- docker-compose-dev.yml
- docker-compose.yml
- opac/manager.py
- opac/tests/test_admin_views.py
- opac/webapp/__init__.py
- opac/webapp/admin/views.py
- opac/webapp/config/default.py
- opac/webapp/static/css/rq_dashboard.css
- opac/webapp/tasks.py
- opac/webapp/templates/admin/email/audit_log_report.html
- opac/webapp/templates/rq_dashboard/base.html
- opac/webapp/templates/rq_dashboard/dashboard.html
- opac/webapp/templates/rq_scheduler_dashboard/base.html
- opac/webapp/templates/rq_scheduler_dashboard/dashboard.html
- opac/webapp/utils/__init__.py
- opac/webapp/utils/utils.py
- requirements.txt
- start_scheduler.sh
- start_worker.sh
> envio de email com relatório diário das mudanças que foram feitas nas páginas informativas

- docker-compose-dev.yml
- opac/tests/test_main_views.py
- opac/webapp/main/views.py
> Tk1020 - Adiciona a capacidade de acesso ao artigo por URL

- docker-compose-dev.yml
- opac/manager.py
- opac/webapp/config/default.py
- opac/webapp/tasks.py
- opac/webapp/utils/utils.py
- Criado comando para limpar as tarefas
- Alterado comando para configurar o scheduler
- Alterado configurador de scheduler
- Criadas variáveis de configuração
> Alteração na configuração do scheduler

- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/webapp/admin/views.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
> [tk1067] Usar slug_name + language para recuperar a página.

- requirements.txt
Corrigi vunerabilidade da requests
> Atualiza a requests

- opac/tests/test_controller.py
- opac/webapp/controllers.py
Apresenta (no sumário) a lista de artigos ahead of print e de publicação contínua do artigo mais recente para o mais antigo
/opac/webapp/controllers.py
Publicação Contínua
Acessar https://new.scielo.br/toc/reeusp/2018.v52/
Os arquivos devem vir a seguinte ordem:
N/A
#987
> [Tk987] Apresenta (no sumário) a lista de artigos ahead of print e de publicação contínua do artigo mais recente para o mais antigo

- opac/webapp/templates/journal/includes/header.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Cria uma checagem na template do journal, para não gerar link caso não haja link para a revista periódico atual ou para a periódico anterior
pelo `journal/includes/header.html`
tentar acessar um periódico não tenha periódico antigo, ex: /journal/abem/ (base `scl`) 
#1117
> Ajustes na template de detalhes de journals

- opac/webapp/templates/article/includes/meta.html
Corrigi o idioma do título do artigo nos meta tags do site para o Google
**opac/webapp/templates/article/includes/meta.html**
```
make dev_compose_up (Projeto OPAC)
```
Não há.
Ticket: #1279 
Não há.
> Corrigi o idioma da tag citation_title

- requirements.txt
Atualiza a versão do packtools. 
https://github.com/scieloorg/packtools/pull/200
> Atualizar a versão do packtools com suporte a 'Resumo Visual'

- requirements.txt
Este pull request atualiza a versão do packtools para 2.5.5.
- `requirements.txt`
Para testar este pull request manualmente deve-se:
- Fazer o build de uma imagem opac utilizando este PR
- Acessar um documento do tipo retratação (http://localhost:8000/article/hoehnea/2018.v45n3/540-540/);
- Verificar que o quadro de retratação foi adicionado com sucesso;
N/A
N/A
N/A
> Atualiza a versão do packtools para 2.5.5

- opac/webapp/main/views.py
Adiciona o idioma no cookie.
* opac/webapp/main/views.py
Manualmente olhando no inspetor, veja: 
Essa demanda surgiu com a necessidade de apresentarmos a mensagem LGPD, veja o ticket: https://github.com/scieloorg/opac/issues/1365
https://github.com/scieloorg/opac/issues/1365
https://github.com/scieloorg/scielo.org/issues/136
> Adiciona o idioma no cookie language

- opac/webapp/config/default.py
- opac/webapp/templates/base.html
Esse PR tem como propósito adiciona no rodapé do site uma mensagem de política de cookie. 
Pode iniciar a revisão pelos arquivos: 
opac/webapp/config/default.py
opac/webapp/templates/base.html
Para testar manualmente sugiro iniciar a aplicação utilizando Docker, utilizando o comando: 
`make dev_compose_up`
O script responsável por adicionar a msg está disponível em: https://static.scielo.org/js/cookiePolicy.min.js
https://github.com/scieloorg/opac/issues/1365
Veja links relacionados a LGPD: https://www.google.com/search?newwindow=1&safe=off&ei=IVC4XeX5AvTM5OUPhZiCsAQ&q=LGPD&oq=LGPD&gs_l=psy-ab.3..0i67j0l3j0i67j0l5.7304.7677..7810...0.2..0.91.94.2......0....1j2..gws-wiz.....0..0i71.CUO0vWZ-t5g&ved=0ahUKEwiljrGl2sHlAhV0JrkGHQWMAEYQ4dUDCAs&uact=5
> Adiciona um javascript responsável por adicionar uma mensagem em 3 idiomas a respeito da politica de Cookie (GDPR).

- opac/tests/test_main_views.py
- opac/webapp/main/views.py
Redirecionar para a página com o idioma padrão (original) se a requisição contiver um idioma inválido
Por commits
Rodando os testes automatizados ou Acessando a página de um artigo ou pdf com idioma inválido
n/a
n/a
#1533
n/a
> Redirecionar para a página com o idioma padrão (original) se a requisição contiver um idioma inválido

- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
Troca a tradução do termo _Sumário_. para _Table of contents_ e _Tabla de contenido_ para as traduções para o inglês e espanhol, respectivamente.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Caso seja instalado diretamente na máquina local será necessário executar `make compile_messages` após aplicar o patch e antes de executar o servidor de aplicação.
n/a
n/a
#859 
n/a
> Troca tradução do termo `Sumário`

- opac/webapp/main/views.py
Faz o redirecionamento para previous ou next, se aplicável, no lugar de simplesmente continuar na "view"
por commits
Acessando quaisquer botões "anterior" e "próximo", exceto se estão nas extremidades, e verificar que há o redirecionamento.
Caso esteja nas extremidades, não haverá redirecionamento, e os dados serão do fascículo na navegação atual.
n/a
n/a
#1658
n/a
> Faz o redirecionamento para previous ou next, se aplicável

- requirements.txt
Atualiza versão de packtools para 2.6.7
n/a
n/a
n/a
n/a
n/a
n/a
> Atualiza versão de packtools para 2.6.7

- opac/webapp/controllers.py
Acrescenta `scielo_issn` para encontrar periódico
Por commits
Veja o #1668
n/a
n/a
#1668 
n/a
> Acrescenta `scielo_issn` para encontrar periódico

- opac/webapp/main/views.py
Remove o acesso a `journal` por `last_issue`, pois causava levantamento de exceção
por commits
Ver #1268
n/a
n/a
closes #1268
n/a
> Resolve problema de acesso às páginas informativas dos periódicos

- docker-compose-dev.yml
- docker-compose.yml
- opac/tests/test_controller.py
- opac/tests/test_main_views.py
- opac/webapp/__init__.py
- opac/webapp/config/default.py
- opac/webapp/controllers.py
- opac/webapp/main/views.py
Este pull request melhora o tempo de resposta para todas as requisições ao Website. 
- Por commits
Uma boa maneira para testar esse pull request é por meio de sucessivas requisições a páginas do website, considere utilizar algo como [replay](github.com/joffilyfe/scielo-replay-http-traffic) ou jmeter;
O ideal seria remover o trecho de código que recupera o objeto `collection` a partir do MongoDB e adiciona ao objeto global `g` para toda e qualquer requisição, porém como primeiro passo a simples contabilização dos 
#1818
> Melhora o tempo de resposta para todas as rotas  do website

- opac/webapp/main/views.py
Resolve o problema de obter 404 ao tentar acessar um artigo com a url  legada com o pid v2 com s minúsculo
por commits
Usar uma url antiga com S minúsculo e ver que não está acessível.
Atualizar com o branch e ver que fica acessível.
n/a
n/a
#1918
n/a
> Resolve o problema de obter 404 ao tentar acessar um artigo com a url antiga com S minúsculo

- opac/webapp/main/views.py
- opac/webapp/templates/issue/base.html
- opac/webapp/templates/issue/toc.html
Prepara o site para apresentar no sumário as tags de estilo dos títulos do artigos e as fórmulas
por commits
Acessar o sumário e verificar que os títulos apresentam itálico, bold, fórmulas, se estiverem presentes no título.
n/a
Do site de desenvolvimento
#1484 
n/a
> Prepara o site para apresentar no sumário as tags de estilo dos títulos do artigos e as fórmulas

- opac/webapp/main/views.py
Resolve acesso para pdf cujo link está quebrado porque falta .pdf
por commits
Ver ticket #1959 
n/a
n/a
#1959 
n/a
> Resolve acesso para pdf cujo link está quebrado porque falta .pdf

- opac/tests/test_legacy_urls.py
- opac/webapp/controllers.py
- requirements.txt
Melhora as consultas que envolvem o campo `scielo_pids`
por commits
Acessando artigos que contenham  valores para `scielo_pids.other`
n/a
n/a
#1977
n/a
> Melhora as consultas que envolvem o campo `scielo_pids`

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/includes/metric_modal.html
Adiciona o Badge Scite.
Através dos commits e acessando de forma manual um artigo que contenha essa métrica.
Acessando o site e clicando no link de métricas no canto inferior esquerdo: 
Importante para apresentar essa métrica é necessário ativa-lo através da variável de ambiente **OPAC_USE_SCITE**
#1974 
https://scite.ai/badge
> Tk1974 - Adiciona o Badge Scite.

- opac/tests/test_main_views.py
- opac/webapp/config/templates/testing.template
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/base.html
- opac/webapp/templates/issue/includes/meta.html
- opac/webapp/templates/journal/includes/meta.html
Melhora os templates para 'social_share' e ajusta erro no **caminho da imagem**.
Pelos commits e pelos testes unitários
Acessando uma página e verificando as tags de 'socia_share'
Relacionado com #1950
> Melhora os templates permitindo manter um padrão de 'social_share' e melhora a infra de teste unitários

- requirements.txt
- setup.py
Disponibiliza dados de Google Scholar 2021
por commits
Visualizar os dados de Google Scholar na página de qualquer periódico.
n/a
n/a
n/a
n/a
> Disponibiliza dados de Google Scholar 2021

- requirements.txt
Erro no scieloh5m5 1.9.6. Reverte para scieloh5m5 1.9.5
> Erro no scieloh5m5 1.9.6. Reverter para scieloh5m5 1.9.5

- opac/tests/test_main_views.py
- opac/webapp/config/default.py
- opac/webapp/templates/article/includes/meta.html
Adiciona os metas necessários do autor para Google na página do artigo.
Por commit.
Sugiro rodar os testes automatizados: 
```
export OPAC_CONFIG="config/templates/testing.template" && python opac/manager.py test
```
Em produção o artigo: https://www.scielo.br/j/cr/a/zyHCzQqtG6dVf5y9RhhgzWn/?lang=en contém os dados de afilização e ORCID nos autores, portanto, ao atualizarmos deve ser possível verificar as seguintes tags em ambiente de produção: 
<meta name="citation_author" content="Arias, Sarah Muñoz">
<meta name="citation_author_affiliation" content="Universidad Tecnológica de Pereira">
<meta name="citation_author_orcid" content="http://orcid.org/0000-0002-3430-5422">
<meta name="citation_author" content="Álvarez, Gloria Edith Guerrero">
<meta name="citation_author_affiliation" …
>  Adiciona os metas necessários do autor para Google na página do artigo.

- opac/webapp/config/default.py
- opac/webapp/main/views.py
Remove a avaliação de variável para remover o **colection** da variável lobal do **flask**.
por commit. 
A consequência de a variável collection não está é a não exibição do endereço. 
Esse bug foi inserido no commit anterior.
N/A
N/A
N/At.
> Remove a avaliação de variavel para remover o colection da variável lobal do flask.

- opac/webapp/templates/collection/index.html
Realiza a avaliação da variável correta no template para remover a faixa de métricas.
> Realiza a avaliação da variável correta no template para remover a faixa de métricas.

- Dockerfile
- Dockerfile-dev
Altera o parâmetro do Gunicorn para trabalhar com Pseudo-Threads assim como explicado no link: https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7
> Altera o parâmetro do Gunicorn para trabalhar com Pseudo-Threads

- opac/webapp/main/views.py
- requirements.txt
Corrigi uma propriedade deprecada e atualiza a versão do **werkzeug**.
Por commit 
Rodando a aplicação e realizando alguma requisição em ajax. 
N/A
N/A
N/A
N/A
> Fix is xhr werkzeug

- opac/tests/test_main_views.py
- opac/webapp/config/default.py
- opac/webapp/config/templates/testing.template
- opac/webapp/main/views.py
Fix cache control nas respostas da requisição. 
Por commit
Rodando a aplicação e verificando o header contém o atributo: **Cache-Control: max-age=604800**
Esse PR também corrige alguns testes e adiciona novos para essa alteração 
N/A
N/A
N/A
> Fix cache control nas respostas da requisição. 

- opac/tests/test_main_views.py
- opac/webapp/templates/article/includes/meta.html
Adiciona no DOI com idioma para indexação da metatags do google.
Por commit.
Acessando a aplicação para um artigo com DOI por idioma, exemplo:  https://www.scielo.br/j/rae/a/mTSNspjDVVkVfz8k3RdPfmx/?lang=en
N/A
Veja a tag no retorno do HTML: 
https://github.com/scieloorg/opac/issues/2236
N/A
> Adiciona no DOI com idioma para indexação da metatags do google.

- opac/webapp/config/default.py
- opac/webapp/templates/article/includes/meta.html
- opac/webapp/templates/includes/metric_modal.html
- opac/webapp/templates/macros/article.html
Corrigi os DOIs e títulos com idiomas na página do artigo.
Por commit.
Sugiro que seja considerado o teste unitário incluído no tíquete: #2236 
N/A 
Veja os títulos traduzidos: 
E os DOI com idioma: 
#2236 
N/A
> Corrigi os DOIs e títulos com idiomas na página do artigo.

- opac/webapp/templates/collection/includes/nav.html
- requirements.txt
Adiciona o link no nav.html e atualiza a versão do opac_schema.
N/A
N/A
N/A
N/A
N/A
N/A
> Adiciona o link no nav.html e atualiza a versão do opac_schema.

- opac/webapp/templates/macros/article.html
Garante que seja apresentado o doi original caso não exista o doi com idioma.
Por commit 
Indico acessa um artigo com e sem doi com idioma para ser avaliado o retorno da tag: 
```
<meta name="citation_doi" content="10.1590/0001-37652021931"></meta>
```
Essa atividade garante que seja sempre apresentado um DOI.
N/A
Essa atividade é uma melhoria da atividade: https://github.com/scieloorg/opac/pull/2241
N/A
> Garante que seja apresentado o DOI original caso não exista o DOI com idioma.

- opac/webapp/config/default.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/includes/metric_modal.html
Ajuste o link para o javcascript do plumx e URL para o Plumx, ajusta a lista de param do link do plumx removendo data-no-link.
Acessando localmente um artigo.
N/A
N/A
N/A
N/A
N/A
> Ajuste o link para o javcascript do plumx e URL para o Plumx, ajusta a lista de param do link do plumx removendo data-no-link.

- opac/webapp/templates/collection/includes/header.html
- opac/webapp/templates/journal/includes/header.html
- opac/webapp/templates/macros/collection.html
Torna as imagens de logo dinâmico.
Por commit.
Sugiro testar rodando localmente.
N/A
N/A
> Torna as imagens de logo dinâmico.

- opac/webapp/config/default.py
- opac/webapp/templates/collection/includes/header.html
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
> Adiciona texto no logo e ajusta a lista de extensões

- opac/webapp/config/default.py
- opac/webapp/templates/includes/error_form.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- opac/webapp/translations/pt_BR.UTF-8/LC_MESSAGES/messages.po
Adiciona um nova opção no formulario de reportar error
Por commit 
Acessando a página inicial do site e visualizando a alteração no modal de reportar error.
N/A
#2468 
N/A
> Adiciona um nova opção no formulario de reportar error

- opac/webapp/templates/issue/toc.html
Garante que a pesquisa pelo autor no search a partir no issue toc sja mais precisa.
Por commit.
Rodando uma instância local e verificando que o ao clicar no autor no issue toc a pesquisa para o search irá com aspas duplas. 
N/A
#2421 
N/A
> Garante que a pesquisa pelo autor no search a partir no issue toc sja mais precisa.

- opac/webapp/templates/article/base.html
- opac/webapp/templates/article/detail.html
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
> Remove referencias para related article template

- opac/webapp/templates/includes/error_form.html
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
- opac/webapp/translations/pt_BR.UTF-8/LC_MESSAGES/messages.po
Altera as opções da lista no reportar error
Por commit 
Acessando a aplicação e a área de reportar erro.
N/A
https://github.com/scieloorg/opac/issues/2468
> Altera a lista de opções para reportar erro.

- opac/webapp/templates/article/includes/related-article.html
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
> Adiciona mais um tipo de related article

- opac/webapp/templates/article/base.html
Garante que todos os termos separados serão avaliados como instituição e adiciona a capacidade de buscar por diferentes separadores.
Por commit.
Para teste manual sugiro que seja utilizado uma instância local com artigo e que seja acessado a página de um artigo. 
Clique em **sobre os autores**
Essa implementação tenta garantir que seja exibido o link para o SCIMAGO, porém existe casos em que a instituição não está presente ou ao percorre a lista de termos é encontrado um termo "amplo" que retorna uma instituição errada. 
Nessa alteração foi garantido a criação de uma lista de termos para pesquisa no SCIMAGO pelos seguintes caracteres **['–', ',', '.', ':']**. 
Exemplos de artigos que não apresentava o SCIMAGO antes desse ajuste, que utilizam **"-"**: …
> Garante que todos os termos separados serão avaliados como instituição e adiciona a capacidade de buscar por diferentes separadores.

- requirements.txt
Atualiza a versão do opac_schema
> Atualiza a versão do opac_schema

- requirements.txt
Adicina o orjson como dependencia
> Adicina o orjson como dependencia

- requirements.txt
> Fix the dependence.

- opac/webapp/controllers.py
Esse erro corrige o Bug: https://github.com/scieloorg/opac/issues/2649
> Adiciona mais um tipo msg no envio de erros.

- opac/webapp/main/views.py
Garante que não haja duplicidade
Por commit 
Acessando a página do issue toc. 
Essa funcionalidade evita que não seja duplicado os idiomas no issue toc, veja esse erro no tíquete: https://github.com/scieloorg/opac/issues/2175
https://github.com/scieloorg/opac/issues/2175
> Garante que não haja duplicidade

- opac/webapp/templates/article/base.html
- requirements.txt
Atualiza a página do artigo com as alterações na lista de instituições e seu correspondente link para o **SCIMAGO INSTITUTION**
Por commit 
Para teste manual sugiro rodar a aplicação localmente e verificar as alterações na página do artigo. 
Essa alteração foi realizada com a intenção de apresentar a lista de instituições e seu respectivo link para o **SCIMAGO**. 
**IMPORTANTE:** Essa alteração somente funciona com uma versão específica do packtools: https://github.com/scieloorg/packtools/commit/9b65872a262430dd90b3c9b9dc7f303032a7901c 
Não existe tíquete para essa alteração.
> Atualiza a página do artigo com as alterações na lista de instituições e seu correspondente link para o SCIMAGO INSTITUTION

- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/journal/includes/levelMenu.html
Ajusta o índice correto para apresentar no resultado de pesquisa os artigos do periódico.
Por commit 
Acesse em ambiente de teste a página do periódico e clique no link **buscar**: 
Analisando foi verificado que o link que é montado no **OPAC** está considerando o **Título abreviado(ta**), quando deveria de considerar o título do periódico(**journal_title**)
N/A
Não há tíquete para essa atividade, essa demanda vou enviado por um usuário.
N/A
> Ajusta o índice correto para apresentar no resultado de pesquisa os artigos do periódico.

- requirements.txt
* Resolve apresentação de fn[@fn-type='data-availability'] e da seção…que destaca a disponibilidade de dados [#493](https://github.com/scieloorg/packtools/pull/493)
* Corrige a ausência do link para o preprint e corrige o rótulo que acompanha o link [#495](https://github.com/scieloorg/packtools/pull/495)
n/a
ver #2832 e #2844
n/a
n/a
fix #2832
fix #2844
n/a
> Adiciona versão de packtools que soluciona bugs de apresentação da página do artigo fn e preprint

- requirements.txt
Atualiza a versão do packtools para apresentar contrib/bio
packtools (ace2e602dfc0c39fd0d023be9701da5dd4d733d7)
por commits
Ver #2856 
n/a
close #2856 
n/a
> Atualiza a versão do packtools para apresentar contrib/bio

- requirements.txt
Altera a versão de packtools que resolve a questão de seção duplicada de disponibilidade de dados
por commit
Ver #2878 
n/a
n/a
Fix #2878 
n/a
> Altera a versão de packtools que resolve a questão de seção duplicada de disponibilidade de dados

- requirements.txt
Corrige ausência de apresentação do rótulo dentro da seção  'Edited by'
por commits
ver #2892 
n/a
ver https://github.com/scieloorg/packtools/pull/545
#2892 
n/a
> Corrige ausência de apresentação do rótulo dentro da seção  'Edited by'

- Dockerfile-dev
- opac/webapp/main/views.py
- requirements.txt
Refatora a função fetch_data
Por commits
Acesso à página de artigos ou a outros componentes fornecidos por outras aplicações (XML, PDF, conteúdo página informativa)
https://www.scielo.br/j/ni/a/MPMYLxwZ3HvFXpPmPvNJNxw/
n/a
n/a
... 
n/a
> Refatora a função fetch_data

- requirements.txt
Atualiza a versão do packtools para apresentar corretamente o menu esquerdo da página do artigo
por commits
ver #2999
n/a
#2999
n/a
> Atualiza a versão do packtools para apresentar corretamente o menu esquerdo da página do artigo

- requirements.txt
Atualiza a versão de packtools para apresentar corretamente letra de música ou poema /  d629d7978cfa1bd432f74069816b62d4b53cd6ac
por commits
Ver #3012 
n/a
n/a
https://github.com/scieloorg/packtools/pull/628
n/a
> Atualiza a versão de packtools para apresentar corretamente letra de música ou poema /  d629d7978cfa1bd432f74069816b62d4b53cd6ac

- requirements.txt
Atualiza a versão de packtools para apresentar corretamente letra de música ou poema /  ~d629d7978cfa1bd432f74069816b62d4b53cd6ac~ . A correta é dd8bb00c08ce5285a4dc00aa7fdb1f3af6b708cb
por commits
Ver #3012 
n/a
n/a
https://github.com/scieloorg/packtools/pull/628
n/a
> Corrige a versão do packtools

- opac/webapp/config/babel.cfg
- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/es/LC_MESSAGES/messages.po
- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
- opac/webapp/translations/es_MX/LC_MESSAGES/messages.po
- opac/webapp/translations/pt_BR.UTF-8/LC_MESSAGES/messages.po
Insere traduções EN/PT relacionadas ao Número anterior e Número seguinte
pelos commits
Acessar alguma página de um periódico e alternar entre os idiomas.
N/A
#3064 
N/A
> Insere traduções EN/ES relacionadas ao Número anterior e Número seguinte

- opac/webapp/templates/base.html
- opac/webapp/templates/includes/clockss.html
- opac/webapp/templates/journal/about.html
Adiciona declaração CLOCKSS no template base
pelos commits
1. Acessar qualquer página html do projeto
N/A
https://github.com/scieloorg/opac/pull/3075
N/A
> Adiciona declaração CLOCKSS no template base
